# This file was auto-generated by Fern from our API Definition.

import json
import typing
from json.decoder import JSONDecodeError

from .. import core
from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.request_options import RequestOptions
from ..core.unchecked_base_model import construct_type
from ..errors.bad_request_error import BadRequestError
from ..errors.not_found_error import NotFoundError
from ..types.company import Company
from .types.get_companies_request_sort import GetCompaniesRequestSort
from .types.get_companies_response import GetCompaniesResponse
from .types.get_crm_attributes_companies_response_item import GetCrmAttributesCompaniesResponseItem
from .types.post_companies_import_response import PostCompaniesImportResponse
from .types.post_companies_response import PostCompaniesResponse
from .types.post_crm_attributes_request_attribute_type import PostCrmAttributesRequestAttributeType
from .types.post_crm_attributes_request_object_type import PostCrmAttributesRequestObjectType
from .types.post_crm_attributes_response import PostCrmAttributesResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawCompaniesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def get_all_companies(
        self,
        *,
        filters: typing.Optional[str] = None,
        linked_contacts_ids: typing.Optional[int] = None,
        linked_deals_ids: typing.Optional[str] = None,
        modified_since: typing.Optional[str] = None,
        created_since: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        sort: typing.Optional[GetCompaniesRequestSort] = None,
        sort_by: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[GetCompaniesResponse]:
        """
        Parameters
        ----------
        filters : typing.Optional[str]
            Filter by attrbutes. If you have filter for owner on your side please send it as {"attributes.owner":"6299dcf3874a14eacbc65c46"}

        linked_contacts_ids : typing.Optional[int]
            Filter by linked contacts ids

        linked_deals_ids : typing.Optional[str]
            Filter by linked Deals ids

        modified_since : typing.Optional[str]
            Filter (urlencoded) the contacts modified after a given UTC date-time (YYYY-MM-DDTHH:mm:ss.SSSZ). Prefer to pass your timezone in date-time format for accurate result.

        created_since : typing.Optional[str]
            Filter (urlencoded) the contacts created after a given UTC date-time (YYYY-MM-DDTHH:mm:ss.SSSZ). Prefer to pass your timezone in date-time format for accurate result.

        page : typing.Optional[int]
            Index of the first document of the page

        limit : typing.Optional[int]
            Number of documents per page

        sort : typing.Optional[GetCompaniesRequestSort]
            Sort the results in the ascending/descending order. Default order is **descending** by creation if `sort` is not passed

        sort_by : typing.Optional[str]
            The field used to sort field names.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GetCompaniesResponse]
            Returns companies list with filters
        """
        _response = self._client_wrapper.httpx_client.request(
            "companies",
            method="GET",
            params={
                "filters": filters,
                "linkedContactsIds": linked_contacts_ids,
                "linkedDealsIds": linked_deals_ids,
                "modifiedSince": modified_since,
                "createdSince": created_since,
                "page": page,
                "limit": limit,
                "sort": sort,
                "sortBy": sort_by,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetCompaniesResponse,
                    construct_type(
                        type_=GetCompaniesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_a_company(
        self,
        *,
        name: str,
        attributes: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        country_code: typing.Optional[int] = OMIT,
        linked_contacts_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        linked_deals_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PostCompaniesResponse]:
        """
        Parameters
        ----------
        name : str
            Name of company

        attributes : typing.Optional[typing.Dict[str, typing.Any]]
            Attributes for company creation

        country_code : typing.Optional[int]
            Country code if phone_number is passed in attributes.

        linked_contacts_ids : typing.Optional[typing.Sequence[int]]
            Contact ids to be linked with company

        linked_deals_ids : typing.Optional[typing.Sequence[str]]
            Deal ids to be linked with company

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PostCompaniesResponse]
            Created new Company
        """
        _response = self._client_wrapper.httpx_client.request(
            "companies",
            method="POST",
            json={
                "attributes": attributes,
                "countryCode": country_code,
                "linkedContactsIds": linked_contacts_ids,
                "linkedDealsIds": linked_deals_ids,
                "name": name,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PostCompaniesResponse,
                    construct_type(
                        type_=PostCompaniesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def import_companies_creation_and_updation(
        self,
        *,
        file: typing.Optional[core.File] = OMIT,
        mapping: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PostCompaniesImportResponse]:
        """
        Import companies from a CSV file with mapping options.

        Parameters
        ----------
        file : typing.Optional[core.File]
            See core.File for more documentation

        mapping : typing.Optional[typing.Dict[str, typing.Any]]
            The mapping options in JSON format. Here is an example of the JSON structure: ```json {
              "link_entities": true, // Determines whether to link related entities during the import process
              "unlink_entities": false, // Determines whether to unlink related entities during the import process
              "update_existing_records": true, // Determines whether to update based on company ID or treat every row as create
              "unset_empty_attributes": false // Determines whether to unset a specific attribute during update if the values input is blank
            } ```

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PostCompaniesImportResponse]
            Successfully imported companies
        """
        _response = self._client_wrapper.httpx_client.request(
            "companies/import",
            method="POST",
            data={
                "mapping": json.dumps(jsonable_encoder(mapping)),
            },
            files={
                **({"file": file} if file is not None else {}),
            },
            request_options=request_options,
            omit=OMIT,
            force_multipart=True,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PostCompaniesImportResponse,
                    construct_type(
                        type_=PostCompaniesImportResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def link_and_unlink_company_with_contact_and_deal(
        self,
        id: str,
        *,
        link_contact_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        link_deals_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        unlink_contact_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        unlink_deals_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[None]:
        """
        Parameters
        ----------
        id : str

        link_contact_ids : typing.Optional[typing.Sequence[int]]
            Contact ids for contacts to be linked with company

        link_deals_ids : typing.Optional[typing.Sequence[str]]
            Deal ids for deals to be linked with company

        unlink_contact_ids : typing.Optional[typing.Sequence[int]]
            Contact ids for contacts to be unlinked from company

        unlink_deals_ids : typing.Optional[typing.Sequence[str]]
            Deal ids for deals to be unlinked from company

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"companies/link-unlink/{jsonable_encoder(id)}",
            method="PATCH",
            json={
                "linkContactIds": link_contact_ids,
                "linkDealsIds": link_deals_ids,
                "unlinkContactIds": unlink_contact_ids,
                "unlinkDealsIds": unlink_deals_ids,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_a_company(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[Company]:
        """
        Parameters
        ----------
        id : str
            Get Company Details

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Company]
            Returns the Company
        """
        _response = self._client_wrapper.httpx_client.request(
            f"companies/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Company,
                    construct_type(
                        type_=Company,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete_a_company(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[None]:
        """
        Parameters
        ----------
        id : str
            Company ID to delete

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"companies/{jsonable_encoder(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update_a_company(
        self,
        id: str,
        *,
        attributes: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        country_code: typing.Optional[int] = OMIT,
        linked_contacts_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        linked_deals_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[Company]:
        """
        Parameters
        ----------
        id : str

        attributes : typing.Optional[typing.Dict[str, typing.Any]]
            Attributes for company update

        country_code : typing.Optional[int]
            Country code if phone_number is passed in attributes.

        linked_contacts_ids : typing.Optional[typing.Sequence[int]]
            Warning - Using PATCH on linkedContactIds replaces the list of linked contacts. Omitted IDs will be removed.

        linked_deals_ids : typing.Optional[typing.Sequence[str]]
            Warning - Using PATCH on linkedDealsIds replaces the list of linked contacts. Omitted IDs will be removed.

        name : typing.Optional[str]
            Name of company

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Company]
            Company updated successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            f"companies/{jsonable_encoder(id)}",
            method="PATCH",
            json={
                "attributes": attributes,
                "countryCode": country_code,
                "linkedContactsIds": linked_contacts_ids,
                "linkedDealsIds": linked_deals_ids,
                "name": name,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Company,
                    construct_type(
                        type_=Company,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_a_company_deal_attribute(
        self,
        *,
        attribute_type: PostCrmAttributesRequestAttributeType,
        label: str,
        object_type: PostCrmAttributesRequestObjectType,
        description: typing.Optional[str] = OMIT,
        options_labels: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PostCrmAttributesResponse]:
        """
        Parameters
        ----------
        attribute_type : PostCrmAttributesRequestAttributeType
            The type of attribute (must be one of the defined enums)

        label : str
            The label for the attribute (max 50 characters, cannot be empty)

        object_type : PostCrmAttributesRequestObjectType
            The type of object the attribute belongs to (prefilled with `companies`, mandatory)

        description : typing.Optional[str]
            A description of the attribute

        options_labels : typing.Optional[typing.Sequence[str]]
            Options for multi-choice or single-select attributes

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PostCrmAttributesResponse]
            Created new attribute
        """
        _response = self._client_wrapper.httpx_client.request(
            "crm/attributes",
            method="POST",
            json={
                "attributeType": attribute_type,
                "description": description,
                "label": label,
                "objectType": object_type,
                "optionsLabels": options_labels,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PostCrmAttributesResponse,
                    construct_type(
                        type_=PostCrmAttributesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_company_attributes(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.List[GetCrmAttributesCompaniesResponseItem]]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.List[GetCrmAttributesCompaniesResponseItem]]
            Returns list of company attributes
        """
        _response = self._client_wrapper.httpx_client.request(
            "crm/attributes/companies",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[GetCrmAttributesCompaniesResponseItem],
                    construct_type(
                        type_=typing.List[GetCrmAttributesCompaniesResponseItem],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawCompaniesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def get_all_companies(
        self,
        *,
        filters: typing.Optional[str] = None,
        linked_contacts_ids: typing.Optional[int] = None,
        linked_deals_ids: typing.Optional[str] = None,
        modified_since: typing.Optional[str] = None,
        created_since: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        sort: typing.Optional[GetCompaniesRequestSort] = None,
        sort_by: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[GetCompaniesResponse]:
        """
        Parameters
        ----------
        filters : typing.Optional[str]
            Filter by attrbutes. If you have filter for owner on your side please send it as {"attributes.owner":"6299dcf3874a14eacbc65c46"}

        linked_contacts_ids : typing.Optional[int]
            Filter by linked contacts ids

        linked_deals_ids : typing.Optional[str]
            Filter by linked Deals ids

        modified_since : typing.Optional[str]
            Filter (urlencoded) the contacts modified after a given UTC date-time (YYYY-MM-DDTHH:mm:ss.SSSZ). Prefer to pass your timezone in date-time format for accurate result.

        created_since : typing.Optional[str]
            Filter (urlencoded) the contacts created after a given UTC date-time (YYYY-MM-DDTHH:mm:ss.SSSZ). Prefer to pass your timezone in date-time format for accurate result.

        page : typing.Optional[int]
            Index of the first document of the page

        limit : typing.Optional[int]
            Number of documents per page

        sort : typing.Optional[GetCompaniesRequestSort]
            Sort the results in the ascending/descending order. Default order is **descending** by creation if `sort` is not passed

        sort_by : typing.Optional[str]
            The field used to sort field names.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GetCompaniesResponse]
            Returns companies list with filters
        """
        _response = await self._client_wrapper.httpx_client.request(
            "companies",
            method="GET",
            params={
                "filters": filters,
                "linkedContactsIds": linked_contacts_ids,
                "linkedDealsIds": linked_deals_ids,
                "modifiedSince": modified_since,
                "createdSince": created_since,
                "page": page,
                "limit": limit,
                "sort": sort,
                "sortBy": sort_by,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetCompaniesResponse,
                    construct_type(
                        type_=GetCompaniesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_a_company(
        self,
        *,
        name: str,
        attributes: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        country_code: typing.Optional[int] = OMIT,
        linked_contacts_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        linked_deals_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PostCompaniesResponse]:
        """
        Parameters
        ----------
        name : str
            Name of company

        attributes : typing.Optional[typing.Dict[str, typing.Any]]
            Attributes for company creation

        country_code : typing.Optional[int]
            Country code if phone_number is passed in attributes.

        linked_contacts_ids : typing.Optional[typing.Sequence[int]]
            Contact ids to be linked with company

        linked_deals_ids : typing.Optional[typing.Sequence[str]]
            Deal ids to be linked with company

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PostCompaniesResponse]
            Created new Company
        """
        _response = await self._client_wrapper.httpx_client.request(
            "companies",
            method="POST",
            json={
                "attributes": attributes,
                "countryCode": country_code,
                "linkedContactsIds": linked_contacts_ids,
                "linkedDealsIds": linked_deals_ids,
                "name": name,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PostCompaniesResponse,
                    construct_type(
                        type_=PostCompaniesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def import_companies_creation_and_updation(
        self,
        *,
        file: typing.Optional[core.File] = OMIT,
        mapping: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PostCompaniesImportResponse]:
        """
        Import companies from a CSV file with mapping options.

        Parameters
        ----------
        file : typing.Optional[core.File]
            See core.File for more documentation

        mapping : typing.Optional[typing.Dict[str, typing.Any]]
            The mapping options in JSON format. Here is an example of the JSON structure: ```json {
              "link_entities": true, // Determines whether to link related entities during the import process
              "unlink_entities": false, // Determines whether to unlink related entities during the import process
              "update_existing_records": true, // Determines whether to update based on company ID or treat every row as create
              "unset_empty_attributes": false // Determines whether to unset a specific attribute during update if the values input is blank
            } ```

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PostCompaniesImportResponse]
            Successfully imported companies
        """
        _response = await self._client_wrapper.httpx_client.request(
            "companies/import",
            method="POST",
            data={
                "mapping": json.dumps(jsonable_encoder(mapping)),
            },
            files={
                **({"file": file} if file is not None else {}),
            },
            request_options=request_options,
            omit=OMIT,
            force_multipart=True,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PostCompaniesImportResponse,
                    construct_type(
                        type_=PostCompaniesImportResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def link_and_unlink_company_with_contact_and_deal(
        self,
        id: str,
        *,
        link_contact_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        link_deals_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        unlink_contact_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        unlink_deals_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[None]:
        """
        Parameters
        ----------
        id : str

        link_contact_ids : typing.Optional[typing.Sequence[int]]
            Contact ids for contacts to be linked with company

        link_deals_ids : typing.Optional[typing.Sequence[str]]
            Deal ids for deals to be linked with company

        unlink_contact_ids : typing.Optional[typing.Sequence[int]]
            Contact ids for contacts to be unlinked from company

        unlink_deals_ids : typing.Optional[typing.Sequence[str]]
            Deal ids for deals to be unlinked from company

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"companies/link-unlink/{jsonable_encoder(id)}",
            method="PATCH",
            json={
                "linkContactIds": link_contact_ids,
                "linkDealsIds": link_deals_ids,
                "unlinkContactIds": unlink_contact_ids,
                "unlinkDealsIds": unlink_deals_ids,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_a_company(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[Company]:
        """
        Parameters
        ----------
        id : str
            Get Company Details

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Company]
            Returns the Company
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"companies/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Company,
                    construct_type(
                        type_=Company,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete_a_company(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[None]:
        """
        Parameters
        ----------
        id : str
            Company ID to delete

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"companies/{jsonable_encoder(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update_a_company(
        self,
        id: str,
        *,
        attributes: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        country_code: typing.Optional[int] = OMIT,
        linked_contacts_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        linked_deals_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[Company]:
        """
        Parameters
        ----------
        id : str

        attributes : typing.Optional[typing.Dict[str, typing.Any]]
            Attributes for company update

        country_code : typing.Optional[int]
            Country code if phone_number is passed in attributes.

        linked_contacts_ids : typing.Optional[typing.Sequence[int]]
            Warning - Using PATCH on linkedContactIds replaces the list of linked contacts. Omitted IDs will be removed.

        linked_deals_ids : typing.Optional[typing.Sequence[str]]
            Warning - Using PATCH on linkedDealsIds replaces the list of linked contacts. Omitted IDs will be removed.

        name : typing.Optional[str]
            Name of company

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Company]
            Company updated successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"companies/{jsonable_encoder(id)}",
            method="PATCH",
            json={
                "attributes": attributes,
                "countryCode": country_code,
                "linkedContactsIds": linked_contacts_ids,
                "linkedDealsIds": linked_deals_ids,
                "name": name,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Company,
                    construct_type(
                        type_=Company,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_a_company_deal_attribute(
        self,
        *,
        attribute_type: PostCrmAttributesRequestAttributeType,
        label: str,
        object_type: PostCrmAttributesRequestObjectType,
        description: typing.Optional[str] = OMIT,
        options_labels: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PostCrmAttributesResponse]:
        """
        Parameters
        ----------
        attribute_type : PostCrmAttributesRequestAttributeType
            The type of attribute (must be one of the defined enums)

        label : str
            The label for the attribute (max 50 characters, cannot be empty)

        object_type : PostCrmAttributesRequestObjectType
            The type of object the attribute belongs to (prefilled with `companies`, mandatory)

        description : typing.Optional[str]
            A description of the attribute

        options_labels : typing.Optional[typing.Sequence[str]]
            Options for multi-choice or single-select attributes

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PostCrmAttributesResponse]
            Created new attribute
        """
        _response = await self._client_wrapper.httpx_client.request(
            "crm/attributes",
            method="POST",
            json={
                "attributeType": attribute_type,
                "description": description,
                "label": label,
                "objectType": object_type,
                "optionsLabels": options_labels,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PostCrmAttributesResponse,
                    construct_type(
                        type_=PostCrmAttributesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_company_attributes(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.List[GetCrmAttributesCompaniesResponseItem]]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.List[GetCrmAttributesCompaniesResponseItem]]
            Returns list of company attributes
        """
        _response = await self._client_wrapper.httpx_client.request(
            "crm/attributes/companies",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[GetCrmAttributesCompaniesResponseItem],
                    construct_type(
                        type_=typing.List[GetCrmAttributesCompaniesResponseItem],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
