# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .get_crm_attributes_deals_response_item import GetCrmAttributesDealsResponseItem
    from .get_crm_deals_request_sort import GetCrmDealsRequestSort
    from .get_crm_deals_response import GetCrmDealsResponse
    from .post_crm_deals_import_response import PostCrmDealsImportResponse
    from .post_crm_deals_response import PostCrmDealsResponse
_dynamic_imports: typing.Dict[str, str] = {
    "GetCrmAttributesDealsResponseItem": ".get_crm_attributes_deals_response_item",
    "GetCrmDealsRequestSort": ".get_crm_deals_request_sort",
    "GetCrmDealsResponse": ".get_crm_deals_response",
    "PostCrmDealsImportResponse": ".post_crm_deals_import_response",
    "PostCrmDealsResponse": ".post_crm_deals_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "GetCrmAttributesDealsResponseItem",
    "GetCrmDealsRequestSort",
    "GetCrmDealsResponse",
    "PostCrmDealsImportResponse",
    "PostCrmDealsResponse",
]
