# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..core.unchecked_base_model import construct_type
from ..errors.bad_request_error import BadRequestError
from ..errors.not_found_error import NotFoundError
from .types.create_whats_app_campaign_request_recipients import CreateWhatsAppCampaignRequestRecipients
from .types.create_whats_app_campaign_response import CreateWhatsAppCampaignResponse
from .types.create_whats_app_template_request_category import CreateWhatsAppTemplateRequestCategory
from .types.create_whats_app_template_request_source import CreateWhatsAppTemplateRequestSource
from .types.create_whats_app_template_response import CreateWhatsAppTemplateResponse
from .types.get_whats_app_campaign_response import GetWhatsAppCampaignResponse
from .types.get_whats_app_campaigns_request_sort import GetWhatsAppCampaignsRequestSort
from .types.get_whats_app_campaigns_response import GetWhatsAppCampaignsResponse
from .types.get_whats_app_config_response import GetWhatsAppConfigResponse
from .types.get_whats_app_templates_request_sort import GetWhatsAppTemplatesRequestSort
from .types.get_whats_app_templates_request_source import GetWhatsAppTemplatesRequestSource
from .types.get_whats_app_templates_response import GetWhatsAppTemplatesResponse
from .types.update_whats_app_campaign_request_campaign_status import UpdateWhatsAppCampaignRequestCampaignStatus
from .types.update_whats_app_campaign_request_recipients import UpdateWhatsAppCampaignRequestRecipients

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawWhatsAppCampaignsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def get_whats_app_campaigns(
        self,
        *,
        start_date: typing.Optional[str] = None,
        end_date: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        sort: typing.Optional[GetWhatsAppCampaignsRequestSort] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[GetWhatsAppCampaignsResponse]:
        """
        Parameters
        ----------
        start_date : typing.Optional[str]
            **Mandatory if endDate is used**. Starting (urlencoded) UTC date-time (YYYY-MM-DDTHH:mm:ss.SSSZ) to filter the WhatsApp campaigns created. **Prefer to pass your timezone in date-time format for accurate result**

        end_date : typing.Optional[str]
            **Mandatory if startDate is used**. Ending (urlencoded) UTC date-time (YYYY-MM-DDTHH:mm:ss.SSSZ) to filter the WhatsApp campaigns created. **Prefer to pass your timezone in date-time format for accurate result**

        limit : typing.Optional[int]
            Number of documents per page

        offset : typing.Optional[int]
            Index of the first document in the page

        sort : typing.Optional[GetWhatsAppCampaignsRequestSort]
            Sort the results in the ascending/descending order of record modification. Default order is **descending** if `sort` is not passed

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GetWhatsAppCampaignsResponse]
            WhatsApp campaigns information
        """
        _response = self._client_wrapper.httpx_client.request(
            "whatsappCampaigns",
            method="GET",
            params={
                "startDate": start_date,
                "endDate": end_date,
                "limit": limit,
                "offset": offset,
                "sort": sort,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetWhatsAppCampaignsResponse,
                    construct_type(
                        type_=GetWhatsAppCampaignsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_whats_app_campaign(
        self,
        *,
        name: str,
        recipients: CreateWhatsAppCampaignRequestRecipients,
        scheduled_at: str,
        template_id: int,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[CreateWhatsAppCampaignResponse]:
        """
        <Note>
        You can use this API for WhatsApp only if you have setup your WhatsApp account on Brevo platform. To setup your WhatsApp account, follow the steps in the guide below.

        [Activating Whatsapp](https://developers.brevo.com/docs/whatsapp-campaigns-1) in your account
        </Note>

        <Note>
        This API requires the List and Segment ids as recipients in Body params. You can use the below Contact endpoints to get the required information.

        [Get all the Lists](https://developers.brevo.com/reference/getlists-1)

        [Get all the Segments](https://developers.brevo.com/reference/getsegments)
        </Note>

        Parameters
        ----------
        name : str
            Name of the WhatsApp campaign creation

        recipients : CreateWhatsAppCampaignRequestRecipients
            Segment ids and List ids to include/exclude from campaign

        scheduled_at : str
            Sending UTC date-time (YYYY-MM-DDTHH:mm:ss.SSSZ). **Prefer to pass your timezone in date-time format for accurate result.For example: **2017-06-01T12:30:00+02:00**

        template_id : int
            Id of the WhatsApp template in **approved** state

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CreateWhatsAppCampaignResponse]
            successfully created
        """
        _response = self._client_wrapper.httpx_client.request(
            "whatsappCampaigns",
            method="POST",
            json={
                "name": name,
                "recipients": convert_and_respect_annotation_metadata(
                    object_=recipients, annotation=CreateWhatsAppCampaignRequestRecipients, direction="write"
                ),
                "scheduledAt": scheduled_at,
                "templateId": template_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateWhatsAppCampaignResponse,
                    construct_type(
                        type_=CreateWhatsAppCampaignResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_whats_app_config(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[GetWhatsAppConfigResponse]:
        """
        <Note>
        You can use this API for WhatsApp only if you have setup your WhatsApp account on Brevo platform. To setup your WhatsApp account, follow the steps in the guide below.

        [Activating WhatsApp](https://developers.brevo.com/docs/whatsapp-campaigns-1) in your account
        </Note>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GetWhatsAppConfigResponse]
            Get all the information of your WhatsApp API account
        """
        _response = self._client_wrapper.httpx_client.request(
            "whatsappCampaigns/config",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetWhatsAppConfigResponse,
                    construct_type(
                        type_=GetWhatsAppConfigResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_whats_app_template(
        self,
        *,
        body_text: str,
        category: CreateWhatsAppTemplateRequestCategory,
        language: str,
        name: str,
        header_text: typing.Optional[str] = OMIT,
        media_url: typing.Optional[str] = OMIT,
        source: typing.Optional[CreateWhatsAppTemplateRequestSource] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[CreateWhatsAppTemplateResponse]:
        """
        <Note>
        You can use this API for WhatsApp only if you have setup your WhatsApp account on Brevo platform. To setup your WhatsApp account, follow the steps in the guide below.

        [Activating WhatsApp](https://developers.brevo.com/docs/whatsapp-campaigns-1) in your account
        </Note>

        Parameters
        ----------
        body_text : str
            Body of the template. **Maximum allowed characters are 1024**

        category : CreateWhatsAppTemplateRequestCategory
            Category of the template

        language : str
            Language of the template. For Example :
            **en** for English

        name : str
            Name of the template

        header_text : typing.Optional[str]
            Text content of the header in the template.  **Maximum allowed characters are 45** **Use this field to add text content in template header and if mediaUrl is empty**

        media_url : typing.Optional[str]
            Absolute url of the media file **(no local file)** for the header. **Use this field in you want to add media in Template header and headerText is empty** Allowed extensions for media files are: #### jpeg | png | mp4 | pdf

        source : typing.Optional[CreateWhatsAppTemplateRequestSource]
            source of the template

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CreateWhatsAppTemplateResponse]
            successfully created
        """
        _response = self._client_wrapper.httpx_client.request(
            "whatsappCampaigns/template",
            method="POST",
            json={
                "bodyText": body_text,
                "category": category,
                "headerText": header_text,
                "language": language,
                "mediaUrl": media_url,
                "name": name,
                "source": source,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateWhatsAppTemplateResponse,
                    construct_type(
                        type_=CreateWhatsAppTemplateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_whats_app_templates(
        self,
        *,
        start_date: typing.Optional[str] = None,
        end_date: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        sort: typing.Optional[GetWhatsAppTemplatesRequestSort] = None,
        source: typing.Optional[GetWhatsAppTemplatesRequestSource] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[GetWhatsAppTemplatesResponse]:
        """
        Parameters
        ----------
        start_date : typing.Optional[str]
            **Mandatory if endDate is used**. Starting (urlencoded) UTC date-time (YYYY-MM-DDTHH:mm:ss.SSSZ) to filter the templates created. **Prefer to pass your timezone in date-time format for accurate result**

        end_date : typing.Optional[str]
            **Mandatory if startDate is used**. Ending (urlencoded) UTC date-time (YYYY-MM-DDTHH:mm:ss.SSSZ) to filter the templates created. **Prefer to pass your timezone in date-time format for accurate result**

        limit : typing.Optional[int]
            Number of documents per page

        offset : typing.Optional[int]
            Index of the first document in the page

        sort : typing.Optional[GetWhatsAppTemplatesRequestSort]
            Sort the results in the ascending/descending order of record modification. Default order is **descending** if `sort` is not passed

        source : typing.Optional[GetWhatsAppTemplatesRequestSource]
            source of the template

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GetWhatsAppTemplatesResponse]
            WhatsApp templates informations
        """
        _response = self._client_wrapper.httpx_client.request(
            "whatsappCampaigns/template-list",
            method="GET",
            params={
                "startDate": start_date,
                "endDate": end_date,
                "limit": limit,
                "offset": offset,
                "sort": sort,
                "source": source,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetWhatsAppTemplatesResponse,
                    construct_type(
                        type_=GetWhatsAppTemplatesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def send_whats_app_template_approval(
        self, template_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[None]:
        """
        <Note>
        You can use this API for WhatsApp only if you have setup your WhatsApp account on Brevo platform. To setup your WhatsApp account, follow the steps in the guide below.

        [Activating WhatsApp](https://developers.brevo.com/docs/whatsapp-campaigns-1) in your account
        </Note>

        Parameters
        ----------
        template_id : int
            id of the template

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"whatsappCampaigns/template/approval/{jsonable_encoder(template_id)}",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_whats_app_campaign(
        self, campaign_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[GetWhatsAppCampaignResponse]:
        """
        <Note>
        You can use this API for WhatsApp only if you have setup your WhatsApp account on Brevo platform. To setup your WhatsApp account, follow the steps in the guide below.

        [Activating Whatsapp](https://developers.brevo.com/docs/whatsapp-campaigns-1) in your account
        </Note>

        Parameters
        ----------
        campaign_id : int
            Id of the campaign

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GetWhatsAppCampaignResponse]
            Get whatsApp campaign information on the basis of campaignId
        """
        _response = self._client_wrapper.httpx_client.request(
            f"whatsappCampaigns/{jsonable_encoder(campaign_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetWhatsAppCampaignResponse,
                    construct_type(
                        type_=GetWhatsAppCampaignResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update_whats_app_campaign(
        self,
        campaign_id: int,
        *,
        campaign_name: typing.Optional[str] = OMIT,
        campaign_status: typing.Optional[UpdateWhatsAppCampaignRequestCampaignStatus] = OMIT,
        recipients: typing.Optional[UpdateWhatsAppCampaignRequestRecipients] = OMIT,
        reschedule_for: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[None]:
        """
        <Note>
        You can use this API for WhatsApp only if you have setup your WhatsApp account on Brevo platform. To setup your WhatsApp account, follow the steps in the guide below.

        [Activating Whatsapp](https://developers.brevo.com/docs/whatsapp-campaigns-1) in your account
        </Note>

        <Note>
        This API requires the List and Segment ids as recipients in Body params. You can use the below Contact endpoints to get the required information.

        [Get all the Lists](https://developers.brevo.com/reference/getlists-1)

        [Get all the Segments](https://developers.brevo.com/reference/getsegments)
        </Note>

        Parameters
        ----------
        campaign_id : int
            id of the campaign

        campaign_name : typing.Optional[str]
            Name of the campaign

        campaign_status : typing.Optional[UpdateWhatsAppCampaignRequestCampaignStatus]
            Status of the campaign

        recipients : typing.Optional[UpdateWhatsAppCampaignRequestRecipients]
            Segment ids and List ids to include/exclude from campaign

        reschedule_for : typing.Optional[str]
            Reschedule the sending UTC date-time (YYYY-MM-DDTHH:mm:ss.SSSZ) of campaign. **Prefer to pass your timezone in date-time format for accurate result.For example: **2017-06-01T12:30:00+02:00** Use this field to update the scheduledAt of any existing draft or scheduled WhatsApp campaign.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"whatsappCampaigns/{jsonable_encoder(campaign_id)}",
            method="PUT",
            json={
                "campaignName": campaign_name,
                "campaignStatus": campaign_status,
                "recipients": convert_and_respect_annotation_metadata(
                    object_=recipients, annotation=UpdateWhatsAppCampaignRequestRecipients, direction="write"
                ),
                "rescheduleFor": reschedule_for,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete_whats_app_campaign(
        self, campaign_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[None]:
        """
        Parameters
        ----------
        campaign_id : int
            id of the campaign

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"whatsappCampaigns/{jsonable_encoder(campaign_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawWhatsAppCampaignsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def get_whats_app_campaigns(
        self,
        *,
        start_date: typing.Optional[str] = None,
        end_date: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        sort: typing.Optional[GetWhatsAppCampaignsRequestSort] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[GetWhatsAppCampaignsResponse]:
        """
        Parameters
        ----------
        start_date : typing.Optional[str]
            **Mandatory if endDate is used**. Starting (urlencoded) UTC date-time (YYYY-MM-DDTHH:mm:ss.SSSZ) to filter the WhatsApp campaigns created. **Prefer to pass your timezone in date-time format for accurate result**

        end_date : typing.Optional[str]
            **Mandatory if startDate is used**. Ending (urlencoded) UTC date-time (YYYY-MM-DDTHH:mm:ss.SSSZ) to filter the WhatsApp campaigns created. **Prefer to pass your timezone in date-time format for accurate result**

        limit : typing.Optional[int]
            Number of documents per page

        offset : typing.Optional[int]
            Index of the first document in the page

        sort : typing.Optional[GetWhatsAppCampaignsRequestSort]
            Sort the results in the ascending/descending order of record modification. Default order is **descending** if `sort` is not passed

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GetWhatsAppCampaignsResponse]
            WhatsApp campaigns information
        """
        _response = await self._client_wrapper.httpx_client.request(
            "whatsappCampaigns",
            method="GET",
            params={
                "startDate": start_date,
                "endDate": end_date,
                "limit": limit,
                "offset": offset,
                "sort": sort,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetWhatsAppCampaignsResponse,
                    construct_type(
                        type_=GetWhatsAppCampaignsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_whats_app_campaign(
        self,
        *,
        name: str,
        recipients: CreateWhatsAppCampaignRequestRecipients,
        scheduled_at: str,
        template_id: int,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[CreateWhatsAppCampaignResponse]:
        """
        <Note>
        You can use this API for WhatsApp only if you have setup your WhatsApp account on Brevo platform. To setup your WhatsApp account, follow the steps in the guide below.

        [Activating Whatsapp](https://developers.brevo.com/docs/whatsapp-campaigns-1) in your account
        </Note>

        <Note>
        This API requires the List and Segment ids as recipients in Body params. You can use the below Contact endpoints to get the required information.

        [Get all the Lists](https://developers.brevo.com/reference/getlists-1)

        [Get all the Segments](https://developers.brevo.com/reference/getsegments)
        </Note>

        Parameters
        ----------
        name : str
            Name of the WhatsApp campaign creation

        recipients : CreateWhatsAppCampaignRequestRecipients
            Segment ids and List ids to include/exclude from campaign

        scheduled_at : str
            Sending UTC date-time (YYYY-MM-DDTHH:mm:ss.SSSZ). **Prefer to pass your timezone in date-time format for accurate result.For example: **2017-06-01T12:30:00+02:00**

        template_id : int
            Id of the WhatsApp template in **approved** state

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CreateWhatsAppCampaignResponse]
            successfully created
        """
        _response = await self._client_wrapper.httpx_client.request(
            "whatsappCampaigns",
            method="POST",
            json={
                "name": name,
                "recipients": convert_and_respect_annotation_metadata(
                    object_=recipients, annotation=CreateWhatsAppCampaignRequestRecipients, direction="write"
                ),
                "scheduledAt": scheduled_at,
                "templateId": template_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateWhatsAppCampaignResponse,
                    construct_type(
                        type_=CreateWhatsAppCampaignResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_whats_app_config(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[GetWhatsAppConfigResponse]:
        """
        <Note>
        You can use this API for WhatsApp only if you have setup your WhatsApp account on Brevo platform. To setup your WhatsApp account, follow the steps in the guide below.

        [Activating WhatsApp](https://developers.brevo.com/docs/whatsapp-campaigns-1) in your account
        </Note>

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GetWhatsAppConfigResponse]
            Get all the information of your WhatsApp API account
        """
        _response = await self._client_wrapper.httpx_client.request(
            "whatsappCampaigns/config",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetWhatsAppConfigResponse,
                    construct_type(
                        type_=GetWhatsAppConfigResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_whats_app_template(
        self,
        *,
        body_text: str,
        category: CreateWhatsAppTemplateRequestCategory,
        language: str,
        name: str,
        header_text: typing.Optional[str] = OMIT,
        media_url: typing.Optional[str] = OMIT,
        source: typing.Optional[CreateWhatsAppTemplateRequestSource] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[CreateWhatsAppTemplateResponse]:
        """
        <Note>
        You can use this API for WhatsApp only if you have setup your WhatsApp account on Brevo platform. To setup your WhatsApp account, follow the steps in the guide below.

        [Activating WhatsApp](https://developers.brevo.com/docs/whatsapp-campaigns-1) in your account
        </Note>

        Parameters
        ----------
        body_text : str
            Body of the template. **Maximum allowed characters are 1024**

        category : CreateWhatsAppTemplateRequestCategory
            Category of the template

        language : str
            Language of the template. For Example :
            **en** for English

        name : str
            Name of the template

        header_text : typing.Optional[str]
            Text content of the header in the template.  **Maximum allowed characters are 45** **Use this field to add text content in template header and if mediaUrl is empty**

        media_url : typing.Optional[str]
            Absolute url of the media file **(no local file)** for the header. **Use this field in you want to add media in Template header and headerText is empty** Allowed extensions for media files are: #### jpeg | png | mp4 | pdf

        source : typing.Optional[CreateWhatsAppTemplateRequestSource]
            source of the template

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CreateWhatsAppTemplateResponse]
            successfully created
        """
        _response = await self._client_wrapper.httpx_client.request(
            "whatsappCampaigns/template",
            method="POST",
            json={
                "bodyText": body_text,
                "category": category,
                "headerText": header_text,
                "language": language,
                "mediaUrl": media_url,
                "name": name,
                "source": source,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateWhatsAppTemplateResponse,
                    construct_type(
                        type_=CreateWhatsAppTemplateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_whats_app_templates(
        self,
        *,
        start_date: typing.Optional[str] = None,
        end_date: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        sort: typing.Optional[GetWhatsAppTemplatesRequestSort] = None,
        source: typing.Optional[GetWhatsAppTemplatesRequestSource] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[GetWhatsAppTemplatesResponse]:
        """
        Parameters
        ----------
        start_date : typing.Optional[str]
            **Mandatory if endDate is used**. Starting (urlencoded) UTC date-time (YYYY-MM-DDTHH:mm:ss.SSSZ) to filter the templates created. **Prefer to pass your timezone in date-time format for accurate result**

        end_date : typing.Optional[str]
            **Mandatory if startDate is used**. Ending (urlencoded) UTC date-time (YYYY-MM-DDTHH:mm:ss.SSSZ) to filter the templates created. **Prefer to pass your timezone in date-time format for accurate result**

        limit : typing.Optional[int]
            Number of documents per page

        offset : typing.Optional[int]
            Index of the first document in the page

        sort : typing.Optional[GetWhatsAppTemplatesRequestSort]
            Sort the results in the ascending/descending order of record modification. Default order is **descending** if `sort` is not passed

        source : typing.Optional[GetWhatsAppTemplatesRequestSource]
            source of the template

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GetWhatsAppTemplatesResponse]
            WhatsApp templates informations
        """
        _response = await self._client_wrapper.httpx_client.request(
            "whatsappCampaigns/template-list",
            method="GET",
            params={
                "startDate": start_date,
                "endDate": end_date,
                "limit": limit,
                "offset": offset,
                "sort": sort,
                "source": source,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetWhatsAppTemplatesResponse,
                    construct_type(
                        type_=GetWhatsAppTemplatesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def send_whats_app_template_approval(
        self, template_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[None]:
        """
        <Note>
        You can use this API for WhatsApp only if you have setup your WhatsApp account on Brevo platform. To setup your WhatsApp account, follow the steps in the guide below.

        [Activating WhatsApp](https://developers.brevo.com/docs/whatsapp-campaigns-1) in your account
        </Note>

        Parameters
        ----------
        template_id : int
            id of the template

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"whatsappCampaigns/template/approval/{jsonable_encoder(template_id)}",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_whats_app_campaign(
        self, campaign_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[GetWhatsAppCampaignResponse]:
        """
        <Note>
        You can use this API for WhatsApp only if you have setup your WhatsApp account on Brevo platform. To setup your WhatsApp account, follow the steps in the guide below.

        [Activating Whatsapp](https://developers.brevo.com/docs/whatsapp-campaigns-1) in your account
        </Note>

        Parameters
        ----------
        campaign_id : int
            Id of the campaign

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GetWhatsAppCampaignResponse]
            Get whatsApp campaign information on the basis of campaignId
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"whatsappCampaigns/{jsonable_encoder(campaign_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetWhatsAppCampaignResponse,
                    construct_type(
                        type_=GetWhatsAppCampaignResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update_whats_app_campaign(
        self,
        campaign_id: int,
        *,
        campaign_name: typing.Optional[str] = OMIT,
        campaign_status: typing.Optional[UpdateWhatsAppCampaignRequestCampaignStatus] = OMIT,
        recipients: typing.Optional[UpdateWhatsAppCampaignRequestRecipients] = OMIT,
        reschedule_for: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[None]:
        """
        <Note>
        You can use this API for WhatsApp only if you have setup your WhatsApp account on Brevo platform. To setup your WhatsApp account, follow the steps in the guide below.

        [Activating Whatsapp](https://developers.brevo.com/docs/whatsapp-campaigns-1) in your account
        </Note>

        <Note>
        This API requires the List and Segment ids as recipients in Body params. You can use the below Contact endpoints to get the required information.

        [Get all the Lists](https://developers.brevo.com/reference/getlists-1)

        [Get all the Segments](https://developers.brevo.com/reference/getsegments)
        </Note>

        Parameters
        ----------
        campaign_id : int
            id of the campaign

        campaign_name : typing.Optional[str]
            Name of the campaign

        campaign_status : typing.Optional[UpdateWhatsAppCampaignRequestCampaignStatus]
            Status of the campaign

        recipients : typing.Optional[UpdateWhatsAppCampaignRequestRecipients]
            Segment ids and List ids to include/exclude from campaign

        reschedule_for : typing.Optional[str]
            Reschedule the sending UTC date-time (YYYY-MM-DDTHH:mm:ss.SSSZ) of campaign. **Prefer to pass your timezone in date-time format for accurate result.For example: **2017-06-01T12:30:00+02:00** Use this field to update the scheduledAt of any existing draft or scheduled WhatsApp campaign.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"whatsappCampaigns/{jsonable_encoder(campaign_id)}",
            method="PUT",
            json={
                "campaignName": campaign_name,
                "campaignStatus": campaign_status,
                "recipients": convert_and_respect_annotation_metadata(
                    object_=recipients, annotation=UpdateWhatsAppCampaignRequestRecipients, direction="write"
                ),
                "rescheduleFor": reschedule_for,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete_whats_app_campaign(
        self, campaign_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[None]:
        """
        Parameters
        ----------
        campaign_id : int
            id of the campaign

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"whatsappCampaigns/{jsonable_encoder(campaign_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
