# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from ...core.unchecked_base_model import UncheckedBaseModel


class CreateEmailCampaignRequestRecipients(UncheckedBaseModel):
    """
    Segment ids and List ids to include/exclude from campaign
    """

    exclusion_list_ids: typing_extensions.Annotated[
        typing.Optional[typing.List[int]],
        FieldMetadata(alias="exclusionListIds"),
        pydantic.Field(alias="exclusionListIds", description="List ids to exclude from the campaign"),
    ] = None
    exclusion_segment_ids: typing_extensions.Annotated[
        typing.Optional[typing.List[int]],
        FieldMetadata(alias="exclusionSegmentIds"),
        pydantic.Field(
            alias="exclusionSegmentIds", description="Segment ids which have to be excluded from a campaign."
        ),
    ] = None
    list_ids: typing_extensions.Annotated[
        typing.Optional[typing.List[int]],
        FieldMetadata(alias="listIds"),
        pydantic.Field(
            alias="listIds", description="**Mandatory if scheduledAt is not empty**. List Ids to send the campaign to"
        ),
    ] = None
    segment_ids: typing_extensions.Annotated[
        typing.Optional[typing.List[int]],
        FieldMetadata(alias="segmentIds"),
        pydantic.Field(
            alias="segmentIds",
            description="**Mandatory if listIds are not used**. Segment ids to send the campaign to.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
