# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .get_email_campaign_response_email_expiration_date_unit import GetEmailCampaignResponseEmailExpirationDateUnit


class GetEmailCampaignResponseEmailExpirationDate(UncheckedBaseModel):
    """
    Expiration date configuration for the email campaign, if set. Contains the duration and unit of the email expiry.
    """

    duration: typing.Optional[int] = pydantic.Field(default=None)
    """
    Duration of the email expiry
    """

    unit: typing.Optional[GetEmailCampaignResponseEmailExpirationDateUnit] = pydantic.Field(default=None)
    """
    Unit of the duration
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
