# This file was auto-generated by Fern from our API Definition.

import typing

UpdateEmailCampaignRequestEmailExpirationDateUnit = typing.Union[typing.Literal["days", "weeks", "months"], typing.Any]
