# This file was auto-generated by Fern from our API Definition.

import typing

CreateTierGroupRequestUpgradeStrategy = typing.Union[
    typing.Literal["real_time", "membership_anniversary", "tier_anniversary"], typing.Any
]
