# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        CreateEmailCampaignRequestEmailExpirationDate,
        CreateEmailCampaignRequestEmailExpirationDateUnit,
        CreateEmailCampaignRequestRecipients,
        CreateEmailCampaignRequestSender,
        CreateEmailCampaignRequestWinnerCriteria,
        CreateEmailCampaignResponse,
        EmailExportRecipientsRequestRecipientsType,
        EmailExportRecipientsResponse,
        GetAbTestCampaignResultResponse,
        GetAbTestCampaignResultResponseClickedLinks,
        GetAbTestCampaignResultResponseStatistics,
        GetAbTestCampaignResultResponseWinningCriteria,
        GetAbTestCampaignResultResponseWinningVersion,
        GetEmailCampaignRequestStatistics,
        GetEmailCampaignResponse,
        GetEmailCampaignResponseSender,
        GetEmailCampaignResponseStatus,
        GetEmailCampaignResponseType,
        GetEmailCampaignsRequestSort,
        GetEmailCampaignsRequestStatistics,
        GetEmailCampaignsRequestStatus,
        GetEmailCampaignsRequestType,
        GetEmailCampaignsResponse,
        GetEmailCampaignsResponseCampaignsItem,
        GetEmailCampaignsResponseCampaignsItemSender,
        GetEmailCampaignsResponseCampaignsItemStatus,
        GetEmailCampaignsResponseCampaignsItemType,
        GetSharedTemplateUrlResponse,
        UpdateEmailCampaignRequestEmailExpirationDate,
        UpdateEmailCampaignRequestEmailExpirationDateUnit,
        UpdateEmailCampaignRequestRecipients,
        UpdateEmailCampaignRequestSender,
        UpdateEmailCampaignRequestWinnerCriteria,
        UploadImageToGalleryResponse,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "CreateEmailCampaignRequestEmailExpirationDate": ".types",
    "CreateEmailCampaignRequestEmailExpirationDateUnit": ".types",
    "CreateEmailCampaignRequestRecipients": ".types",
    "CreateEmailCampaignRequestSender": ".types",
    "CreateEmailCampaignRequestWinnerCriteria": ".types",
    "CreateEmailCampaignResponse": ".types",
    "EmailExportRecipientsRequestRecipientsType": ".types",
    "EmailExportRecipientsResponse": ".types",
    "GetAbTestCampaignResultResponse": ".types",
    "GetAbTestCampaignResultResponseClickedLinks": ".types",
    "GetAbTestCampaignResultResponseStatistics": ".types",
    "GetAbTestCampaignResultResponseWinningCriteria": ".types",
    "GetAbTestCampaignResultResponseWinningVersion": ".types",
    "GetEmailCampaignRequestStatistics": ".types",
    "GetEmailCampaignResponse": ".types",
    "GetEmailCampaignResponseSender": ".types",
    "GetEmailCampaignResponseStatus": ".types",
    "GetEmailCampaignResponseType": ".types",
    "GetEmailCampaignsRequestSort": ".types",
    "GetEmailCampaignsRequestStatistics": ".types",
    "GetEmailCampaignsRequestStatus": ".types",
    "GetEmailCampaignsRequestType": ".types",
    "GetEmailCampaignsResponse": ".types",
    "GetEmailCampaignsResponseCampaignsItem": ".types",
    "GetEmailCampaignsResponseCampaignsItemSender": ".types",
    "GetEmailCampaignsResponseCampaignsItemStatus": ".types",
    "GetEmailCampaignsResponseCampaignsItemType": ".types",
    "GetSharedTemplateUrlResponse": ".types",
    "UpdateEmailCampaignRequestEmailExpirationDate": ".types",
    "UpdateEmailCampaignRequestEmailExpirationDateUnit": ".types",
    "UpdateEmailCampaignRequestRecipients": ".types",
    "UpdateEmailCampaignRequestSender": ".types",
    "UpdateEmailCampaignRequestWinnerCriteria": ".types",
    "UploadImageToGalleryResponse": ".types",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateEmailCampaignRequestEmailExpirationDate",
    "CreateEmailCampaignRequestEmailExpirationDateUnit",
    "CreateEmailCampaignRequestRecipients",
    "CreateEmailCampaignRequestSender",
    "CreateEmailCampaignRequestWinnerCriteria",
    "CreateEmailCampaignResponse",
    "EmailExportRecipientsRequestRecipientsType",
    "EmailExportRecipientsResponse",
    "GetAbTestCampaignResultResponse",
    "GetAbTestCampaignResultResponseClickedLinks",
    "GetAbTestCampaignResultResponseStatistics",
    "GetAbTestCampaignResultResponseWinningCriteria",
    "GetAbTestCampaignResultResponseWinningVersion",
    "GetEmailCampaignRequestStatistics",
    "GetEmailCampaignResponse",
    "GetEmailCampaignResponseSender",
    "GetEmailCampaignResponseStatus",
    "GetEmailCampaignResponseType",
    "GetEmailCampaignsRequestSort",
    "GetEmailCampaignsRequestStatistics",
    "GetEmailCampaignsRequestStatus",
    "GetEmailCampaignsRequestType",
    "GetEmailCampaignsResponse",
    "GetEmailCampaignsResponseCampaignsItem",
    "GetEmailCampaignsResponseCampaignsItemSender",
    "GetEmailCampaignsResponseCampaignsItemStatus",
    "GetEmailCampaignsResponseCampaignsItemType",
    "GetSharedTemplateUrlResponse",
    "UpdateEmailCampaignRequestEmailExpirationDate",
    "UpdateEmailCampaignRequestEmailExpirationDateUnit",
    "UpdateEmailCampaignRequestRecipients",
    "UpdateEmailCampaignRequestSender",
    "UpdateEmailCampaignRequestWinnerCriteria",
    "UploadImageToGalleryResponse",
]
