# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from ...core.unchecked_base_model import UncheckedBaseModel


class SendWhatsappMessageRequestParams(UncheckedBaseModel):
    contact_numbers: typing_extensions.Annotated[
        typing.List[str],
        FieldMetadata(alias="contactNumbers"),
        pydantic.Field(alias="contactNumbers", description="List of phone numbers of the contacts"),
    ]
    params: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Pass the set of attributes to customize the template. For example, {"FNAME":"Joe", "LNAME":"Doe"}.
    """

    sender_number: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="senderNumber"),
        pydantic.Field(alias="senderNumber", description="WhatsApp Number with country code. Example, 85264318721"),
    ]
    template_id: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="templateId"),
        pydantic.Field(alias="templateId", description="ID of the template to send"),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
