# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .get_scheduled_email_by_id_response_batches_batches_item import GetScheduledEmailByIdResponseBatchesBatchesItem


class GetScheduledEmailByIdResponseBatches(UncheckedBaseModel):
    batches: typing.Optional[typing.List[GetScheduledEmailByIdResponseBatchesBatchesItem]] = None
    count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total number of batches
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
