# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from ...core.unchecked_base_model import UncheckedBaseModel


class PostPreviewSmtpEmailTemplatesRequestParams(UncheckedBaseModel):
    """
    Key-value pairs of dynamic parameters for template rendering.(Required if email not provided) For example: **{"Firstname":"John", "Lastname":"Doe"}**
    """

    firstname: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="Firstname"),
        pydantic.Field(alias="Firstname", description="firstname of the contact. **Dynamic parameter**"),
    ] = None
    lastname: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="Lastname"),
        pydantic.Field(alias="Lastname", description="Lastname of the contact. **Dynamic parameter**"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
