# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .get_account_activity_response import GetAccountActivityResponse
    from .get_account_activity_response_logs_item import GetAccountActivityResponseLogsItem
    from .get_account_response import GetAccountResponse
    from .get_account_response_address import GetAccountResponseAddress
    from .get_account_response_date_time_preferences import GetAccountResponseDateTimePreferences
    from .get_account_response_marketing_automation import GetAccountResponseMarketingAutomation
    from .get_account_response_plan_item import GetAccountResponsePlanItem
    from .get_account_response_plan_item_type import GetAccountResponsePlanItemType
    from .get_account_response_plan_verticals_item import GetAccountResponsePlanVerticalsItem
    from .get_account_response_plan_verticals_item_plan_category import GetAccountResponsePlanVerticalsItemPlanCategory
    from .get_account_response_plan_verticals_item_status import GetAccountResponsePlanVerticalsItemStatus
    from .get_account_response_plan_verticals_item_users import GetAccountResponsePlanVerticalsItemUsers
    from .get_account_response_relay import GetAccountResponseRelay
    from .get_account_response_relay_data import GetAccountResponseRelayData
_dynamic_imports: typing.Dict[str, str] = {
    "GetAccountActivityResponse": ".get_account_activity_response",
    "GetAccountActivityResponseLogsItem": ".get_account_activity_response_logs_item",
    "GetAccountResponse": ".get_account_response",
    "GetAccountResponseAddress": ".get_account_response_address",
    "GetAccountResponseDateTimePreferences": ".get_account_response_date_time_preferences",
    "GetAccountResponseMarketingAutomation": ".get_account_response_marketing_automation",
    "GetAccountResponsePlanItem": ".get_account_response_plan_item",
    "GetAccountResponsePlanItemType": ".get_account_response_plan_item_type",
    "GetAccountResponsePlanVerticalsItem": ".get_account_response_plan_verticals_item",
    "GetAccountResponsePlanVerticalsItemPlanCategory": ".get_account_response_plan_verticals_item_plan_category",
    "GetAccountResponsePlanVerticalsItemStatus": ".get_account_response_plan_verticals_item_status",
    "GetAccountResponsePlanVerticalsItemUsers": ".get_account_response_plan_verticals_item_users",
    "GetAccountResponseRelay": ".get_account_response_relay",
    "GetAccountResponseRelayData": ".get_account_response_relay_data",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "GetAccountActivityResponse",
    "GetAccountActivityResponseLogsItem",
    "GetAccountResponse",
    "GetAccountResponseAddress",
    "GetAccountResponseDateTimePreferences",
    "GetAccountResponseMarketingAutomation",
    "GetAccountResponsePlanItem",
    "GetAccountResponsePlanItemType",
    "GetAccountResponsePlanVerticalsItem",
    "GetAccountResponsePlanVerticalsItemPlanCategory",
    "GetAccountResponsePlanVerticalsItemStatus",
    "GetAccountResponsePlanVerticalsItemUsers",
    "GetAccountResponseRelay",
    "GetAccountResponseRelayData",
]
