# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from ...core.unchecked_base_model import UncheckedBaseModel


class GetAccountResponseRelayData(UncheckedBaseModel):
    """
    Data regarding the transactional email account
    """

    port: int = pydantic.Field()
    """
    Port used for SMTP Relay
    """

    relay: str = pydantic.Field()
    """
    URL of the SMTP Relay
    """

    user_name: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="userName"),
        pydantic.Field(alias="userName", description="Email to use as login on transactional platform"),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
