# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from ...core.unchecked_base_model import UncheckedBaseModel
from .get_external_feed_by_uuid_response_auth_type import GetExternalFeedByUuidResponseAuthType
from .get_external_feed_by_uuid_response_headers_item import GetExternalFeedByUuidResponseHeadersItem


class GetExternalFeedByUuidResponse(UncheckedBaseModel):
    id: str = pydantic.Field()
    """
    Unique identifier of the feed
    """

    name: str = pydantic.Field()
    """
    Name of the feed
    """

    url: str = pydantic.Field()
    """
    URL of the external data source
    """

    auth_type: typing_extensions.Annotated[
        GetExternalFeedByUuidResponseAuthType,
        FieldMetadata(alias="authType"),
        pydantic.Field(alias="authType", description="Authentication type for accessing the feed"),
    ]
    username: typing.Optional[str] = pydantic.Field(default=None)
    """
    Username for basic authentication (null if not using basic auth)
    """

    password: typing.Optional[str] = pydantic.Field(default=None)
    """
    Password for basic authentication (null if not using basic auth)
    """

    token: typing.Optional[str] = pydantic.Field(default=None)
    """
    Token for token-based authentication (null if not using token auth)
    """

    personalization: bool = pydantic.Field()
    """
    Whether personalization is enabled for this feed
    """

    default_attr: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="defaultAttr"),
        pydantic.Field(
            alias="defaultAttr",
            description="Default attribute name for personalization fallback (empty string if not set)",
        ),
    ]
    default_contact: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="defaultContact"),
        pydantic.Field(
            alias="defaultContact",
            description="Default contact email for personalization fallback (empty string if not set)",
        ),
    ]
    headers: typing.Optional[typing.List[GetExternalFeedByUuidResponseHeadersItem]] = pydantic.Field(default=None)
    """
    Custom HTTP headers for the feed request
    """

    max_retries: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="maxRetries"),
        pydantic.Field(alias="maxRetries", description="Maximum number of retry attempts for failed requests"),
    ]
    cache: bool = pydantic.Field()
    """
    Whether to cache the feed response
    """

    created_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="Feed creation timestamp"),
    ]
    modified_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="modifiedAt"),
        pydantic.Field(alias="modifiedAt", description="Feed last modification timestamp"),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
