# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .get_invited_users_list_response_users_item_feature_access import GetInvitedUsersListResponseUsersItemFeatureAccess


class GetInvitedUsersListResponseUsersItem(UncheckedBaseModel):
    email: str = pydantic.Field()
    """
    Email address of the user.
    """

    feature_access: GetInvitedUsersListResponseUsersItemFeatureAccess = pydantic.Field()
    """
    Feature accessiblity given to the user.
    """

    is_owner: str = pydantic.Field()
    """
    Flag for indicating is user owner of the organization.
    """

    status: str = pydantic.Field()
    """
    Status of the invited user.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
