# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .get_lp_list_request_sort_field import GetLpListRequestSortField
    from .get_lp_list_response import GetLpListResponse
    from .get_parameter_subscription_info_response import GetParameterSubscriptionInfoResponse
    from .get_parameter_subscription_info_response_balance import GetParameterSubscriptionInfoResponseBalance
    from .get_parameter_subscription_info_response_balance_balances_item import (
        GetParameterSubscriptionInfoResponseBalanceBalancesItem,
    )
    from .get_parameter_subscription_info_response_members_item import GetParameterSubscriptionInfoResponseMembersItem
    from .get_parameter_subscription_info_response_reward_item import GetParameterSubscriptionInfoResponseRewardItem
    from .get_parameter_subscription_info_response_tier_item import GetParameterSubscriptionInfoResponseTierItem
    from .subscribe_member_to_a_subscription_response import SubscribeMemberToASubscriptionResponse
    from .subscribe_to_loyalty_program_response import SubscribeToLoyaltyProgramResponse
_dynamic_imports: typing.Dict[str, str] = {
    "GetLpListRequestSortField": ".get_lp_list_request_sort_field",
    "GetLpListResponse": ".get_lp_list_response",
    "GetParameterSubscriptionInfoResponse": ".get_parameter_subscription_info_response",
    "GetParameterSubscriptionInfoResponseBalance": ".get_parameter_subscription_info_response_balance",
    "GetParameterSubscriptionInfoResponseBalanceBalancesItem": ".get_parameter_subscription_info_response_balance_balances_item",
    "GetParameterSubscriptionInfoResponseMembersItem": ".get_parameter_subscription_info_response_members_item",
    "GetParameterSubscriptionInfoResponseRewardItem": ".get_parameter_subscription_info_response_reward_item",
    "GetParameterSubscriptionInfoResponseTierItem": ".get_parameter_subscription_info_response_tier_item",
    "SubscribeMemberToASubscriptionResponse": ".subscribe_member_to_a_subscription_response",
    "SubscribeToLoyaltyProgramResponse": ".subscribe_to_loyalty_program_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "GetLpListRequestSortField",
    "GetLpListResponse",
    "GetParameterSubscriptionInfoResponse",
    "GetParameterSubscriptionInfoResponseBalance",
    "GetParameterSubscriptionInfoResponseBalanceBalancesItem",
    "GetParameterSubscriptionInfoResponseMembersItem",
    "GetParameterSubscriptionInfoResponseRewardItem",
    "GetParameterSubscriptionInfoResponseTierItem",
    "SubscribeMemberToASubscriptionResponse",
    "SubscribeToLoyaltyProgramResponse",
]
