# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from ...core.unchecked_base_model import UncheckedBaseModel


class GetParameterSubscriptionInfoResponseTierItem(UncheckedBaseModel):
    contact_id: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="contactId"),
        pydantic.Field(alias="contactId", description="Unique identifier of the contact."),
    ] = None
    created_at: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="Timestamp when the tier was assigned."),
    ] = None
    group_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="groupId"),
        pydantic.Field(alias="groupId", description="Unique identifier of the group associated with the tier."),
    ] = None
    loyalty_program_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="loyaltyProgramId"),
        pydantic.Field(alias="loyaltyProgramId", description="Unique identifier of the loyalty program."),
    ] = None
    meta: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Additional metadata related to the tier.
    """

    tier_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="tierId"),
        pydantic.Field(alias="tierId", description="Unique identifier of the tier."),
    ] = None
    updated_at: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="updatedAt"),
        pydantic.Field(alias="updatedAt", description="Timestamp when the tier was last updated"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
