# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from ...core.unchecked_base_model import UncheckedBaseModel
from .get_parameter_subscription_info_response_balance_balances_item import (
    GetParameterSubscriptionInfoResponseBalanceBalancesItem,
)


class GetParameterSubscriptionInfoResponseBalance(UncheckedBaseModel):
    balances: typing.Optional[typing.List[GetParameterSubscriptionInfoResponseBalanceBalancesItem]] = pydantic.Field(
        default=None
    )
    """
    List of balance details associated with the contact.
    """

    contact_id: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="contactId"),
        pydantic.Field(alias="contactId", description="Unique identifier of the contact."),
    ] = None
    loyalty_program_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="loyaltyProgramId"),
        pydantic.Field(alias="loyaltyProgramId", description="Unique identifier of the loyalty program."),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
