# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from ...core.unchecked_base_model import UncheckedBaseModel
from .get_parameter_subscription_info_response_balance import GetParameterSubscriptionInfoResponseBalance
from .get_parameter_subscription_info_response_members_item import GetParameterSubscriptionInfoResponseMembersItem
from .get_parameter_subscription_info_response_membership import GetParameterSubscriptionInfoResponseMembership
from .get_parameter_subscription_info_response_reward_item import GetParameterSubscriptionInfoResponseRewardItem
from .get_parameter_subscription_info_response_tier_item import GetParameterSubscriptionInfoResponseTierItem


class GetParameterSubscriptionInfoResponse(UncheckedBaseModel):
    balance: typing.Optional[GetParameterSubscriptionInfoResponseBalance] = pydantic.Field(default=None)
    """
    Balance details for the subscription.
    """

    loyalty_program_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="loyaltyProgramName"),
        pydantic.Field(alias="loyaltyProgramName", description="Name of the loyalty program."),
    ] = None
    members: typing.Optional[typing.List[GetParameterSubscriptionInfoResponseMembersItem]] = pydantic.Field(
        default=None
    )
    """
    List of members associated with the subscription.
    """

    membership: typing.Optional[GetParameterSubscriptionInfoResponseMembership] = pydantic.Field(default=None)
    """
    Membership details of the subscription. Returned when the subscription could be resolved from the provided `contactId` or `loyaltySubscriptionId`.
    """

    reward: typing.Optional[typing.List[GetParameterSubscriptionInfoResponseRewardItem]] = pydantic.Field(default=None)
    """
    List of rewards associated with the subscription.
    """

    tier: typing.Optional[typing.List[GetParameterSubscriptionInfoResponseTierItem]] = pydantic.Field(default=None)
    """
    List of tier assignments for the subscription.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
