# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .authenticate_domain_response import AuthenticateDomainResponse
    from .create_domain_response import CreateDomainResponse
    from .create_domain_response_dns_records import CreateDomainResponseDnsRecords
    from .create_domain_response_dns_records_brevo_code import CreateDomainResponseDnsRecordsBrevoCode
    from .create_domain_response_dns_records_dkim_record import CreateDomainResponseDnsRecordsDkimRecord
    from .create_domain_response_dns_records_dmarc_record import CreateDomainResponseDnsRecordsDmarcRecord
    from .get_domain_configuration_response import GetDomainConfigurationResponse
    from .get_domain_configuration_response_dns_records import GetDomainConfigurationResponseDnsRecords
    from .get_domain_configuration_response_dns_records_brevo_code import (
        GetDomainConfigurationResponseDnsRecordsBrevoCode,
    )
    from .get_domain_configuration_response_dns_records_dkim_record import (
        GetDomainConfigurationResponseDnsRecordsDkimRecord,
    )
    from .get_domain_configuration_response_dns_records_dmarc_record import (
        GetDomainConfigurationResponseDnsRecordsDmarcRecord,
    )
    from .get_domains_response import GetDomainsResponse
    from .get_domains_response_domains_item import GetDomainsResponseDomainsItem
    from .get_domains_response_domains_item_creator import GetDomainsResponseDomainsItemCreator
_dynamic_imports: typing.Dict[str, str] = {
    "AuthenticateDomainResponse": ".authenticate_domain_response",
    "CreateDomainResponse": ".create_domain_response",
    "CreateDomainResponseDnsRecords": ".create_domain_response_dns_records",
    "CreateDomainResponseDnsRecordsBrevoCode": ".create_domain_response_dns_records_brevo_code",
    "CreateDomainResponseDnsRecordsDkimRecord": ".create_domain_response_dns_records_dkim_record",
    "CreateDomainResponseDnsRecordsDmarcRecord": ".create_domain_response_dns_records_dmarc_record",
    "GetDomainConfigurationResponse": ".get_domain_configuration_response",
    "GetDomainConfigurationResponseDnsRecords": ".get_domain_configuration_response_dns_records",
    "GetDomainConfigurationResponseDnsRecordsBrevoCode": ".get_domain_configuration_response_dns_records_brevo_code",
    "GetDomainConfigurationResponseDnsRecordsDkimRecord": ".get_domain_configuration_response_dns_records_dkim_record",
    "GetDomainConfigurationResponseDnsRecordsDmarcRecord": ".get_domain_configuration_response_dns_records_dmarc_record",
    "GetDomainsResponse": ".get_domains_response",
    "GetDomainsResponseDomainsItem": ".get_domains_response_domains_item",
    "GetDomainsResponseDomainsItemCreator": ".get_domains_response_domains_item_creator",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AuthenticateDomainResponse",
    "CreateDomainResponse",
    "CreateDomainResponseDnsRecords",
    "CreateDomainResponseDnsRecordsBrevoCode",
    "CreateDomainResponseDnsRecordsDkimRecord",
    "CreateDomainResponseDnsRecordsDmarcRecord",
    "GetDomainConfigurationResponse",
    "GetDomainConfigurationResponseDnsRecords",
    "GetDomainConfigurationResponseDnsRecordsBrevoCode",
    "GetDomainConfigurationResponseDnsRecordsDkimRecord",
    "GetDomainConfigurationResponseDnsRecordsDmarcRecord",
    "GetDomainsResponse",
    "GetDomainsResponseDomainsItem",
    "GetDomainsResponseDomainsItemCreator",
]
