# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel


class GetIpsFromSenderResponseIpsItem(UncheckedBaseModel):
    domain: str = pydantic.Field()
    """
    Domain associated to the IP
    """

    id: int = pydantic.Field()
    """
    ID of the dedicated IP
    """

    ip: str = pydantic.Field()
    """
    Dedicated IP address
    """

    weight: int = pydantic.Field()
    """
    Weight of the IP for this sender
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
