# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        CreateBatchOrderResponse,
        CreateProductAlertRequestContactIdentifiers,
        CreateUpdateBatchCategoryRequestCategoriesItem,
        CreateUpdateBatchCategoryResponse,
        CreateUpdateBatchProductsRequestProductsItem,
        CreateUpdateBatchProductsRequestProductsItemMetaInfoValue,
        CreateUpdateBatchProductsResponse,
        CreateUpdateCategoryResponse,
        CreateUpdateProductRequestMetaInfoValue,
        CreateUpdateProductResponse,
        GetCategoriesRequestSort,
        GetCategoriesResponse,
        GetEcommerceAttributionMetricsConversionSourceConversionSourceIdRequestConversionSource,
        GetEcommerceAttributionMetricsConversionSourceConversionSourceIdResponse,
        GetEcommerceAttributionMetricsConversionSourceConversionSourceIdResponseConversionSource,
        GetEcommerceAttributionMetricsResponse,
        GetEcommerceAttributionMetricsResponseTotals,
        GetEcommerceAttributionProductsConversionSourceConversionSourceIdRequestConversionSource,
        GetEcommerceAttributionProductsConversionSourceConversionSourceIdResponse,
        GetEcommerceAttributionProductsConversionSourceConversionSourceIdResponseProductsItem,
        GetEcommerceConfigDisplayCurrencyResponse,
        GetOrdersRequestSort,
        GetProductsRequestSort,
        GetProductsResponse,
        SetConfigDisplayCurrencyResponse,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "CreateBatchOrderResponse": ".types",
    "CreateProductAlertRequestContactIdentifiers": ".types",
    "CreateUpdateBatchCategoryRequestCategoriesItem": ".types",
    "CreateUpdateBatchCategoryResponse": ".types",
    "CreateUpdateBatchProductsRequestProductsItem": ".types",
    "CreateUpdateBatchProductsRequestProductsItemMetaInfoValue": ".types",
    "CreateUpdateBatchProductsResponse": ".types",
    "CreateUpdateCategoryResponse": ".types",
    "CreateUpdateProductRequestMetaInfoValue": ".types",
    "CreateUpdateProductResponse": ".types",
    "GetCategoriesRequestSort": ".types",
    "GetCategoriesResponse": ".types",
    "GetEcommerceAttributionMetricsConversionSourceConversionSourceIdRequestConversionSource": ".types",
    "GetEcommerceAttributionMetricsConversionSourceConversionSourceIdResponse": ".types",
    "GetEcommerceAttributionMetricsConversionSourceConversionSourceIdResponseConversionSource": ".types",
    "GetEcommerceAttributionMetricsResponse": ".types",
    "GetEcommerceAttributionMetricsResponseTotals": ".types",
    "GetEcommerceAttributionProductsConversionSourceConversionSourceIdRequestConversionSource": ".types",
    "GetEcommerceAttributionProductsConversionSourceConversionSourceIdResponse": ".types",
    "GetEcommerceAttributionProductsConversionSourceConversionSourceIdResponseProductsItem": ".types",
    "GetEcommerceConfigDisplayCurrencyResponse": ".types",
    "GetOrdersRequestSort": ".types",
    "GetProductsRequestSort": ".types",
    "GetProductsResponse": ".types",
    "SetConfigDisplayCurrencyResponse": ".types",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateBatchOrderResponse",
    "CreateProductAlertRequestContactIdentifiers",
    "CreateUpdateBatchCategoryRequestCategoriesItem",
    "CreateUpdateBatchCategoryResponse",
    "CreateUpdateBatchProductsRequestProductsItem",
    "CreateUpdateBatchProductsRequestProductsItemMetaInfoValue",
    "CreateUpdateBatchProductsResponse",
    "CreateUpdateCategoryResponse",
    "CreateUpdateProductRequestMetaInfoValue",
    "CreateUpdateProductResponse",
    "GetCategoriesRequestSort",
    "GetCategoriesResponse",
    "GetEcommerceAttributionMetricsConversionSourceConversionSourceIdRequestConversionSource",
    "GetEcommerceAttributionMetricsConversionSourceConversionSourceIdResponse",
    "GetEcommerceAttributionMetricsConversionSourceConversionSourceIdResponseConversionSource",
    "GetEcommerceAttributionMetricsResponse",
    "GetEcommerceAttributionMetricsResponseTotals",
    "GetEcommerceAttributionProductsConversionSourceConversionSourceIdRequestConversionSource",
    "GetEcommerceAttributionProductsConversionSourceConversionSourceIdResponse",
    "GetEcommerceAttributionProductsConversionSourceConversionSourceIdResponseProductsItem",
    "GetEcommerceConfigDisplayCurrencyResponse",
    "GetOrdersRequestSort",
    "GetProductsRequestSort",
    "GetProductsResponse",
    "SetConfigDisplayCurrencyResponse",
]
