# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel


class UpsertrecordsRequestRecordsItemAssociationsItemRecordsItemIdentifiers(UncheckedBaseModel):
    """
    Identifiers for the associated object record. Provide either `ext_id` or `id`.
    """

    ext_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    External ID of the associated record in your system.
    """

    id: typing.Optional[int] = pydantic.Field(default=None)
    """
    Internal ID of the associated object record generated by Brevo.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
