# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .upsertrecords_request_records_item_associations_item_zero_records_item import (
    UpsertrecordsRequestRecordsItemAssociationsItemZeroRecordsItem,
)


class UpsertrecordsRequestRecordsItemAssociationsItemZero(UncheckedBaseModel):
    object_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Type of the associated object
    """

    records: typing.Optional[typing.List[UpsertrecordsRequestRecordsItemAssociationsItemZeroRecordsItem]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
