# This file was auto-generated by Fern from our API Definition.

import typing

GetLoyaltyBalanceProgramsPidTransactionHistoryRequestStatus = typing.Union[
    typing.Literal["draft", "completed", "rejected", "cancelled", "expired"], typing.Any
]
