# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from ...core.unchecked_base_model import UncheckedBaseModel


class PostLoyaltyBalanceProgramsPidSubscriptionsCidBalancesResponse(UncheckedBaseModel):
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique identifier for the balance.
    """

    amount: typing.Optional[float] = pydantic.Field(default=None)
    """
    The current amount available in the balance.
    """

    loyalty_program_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="loyaltyProgramId"),
        pydantic.Field(alias="loyaltyProgramId", description="Loyalty program ID."),
    ] = None
    organization_id: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="organizationId"),
        pydantic.Field(alias="organizationId", description="Organization ID."),
    ] = None
    contact_id: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="contactId"),
        pydantic.Field(alias="contactId", description="Contact ID."),
    ] = None
    balance_definition_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="balanceDefinitionId"),
        pydantic.Field(alias="balanceDefinitionId", description="Balance definition ID."),
    ] = None
    created_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="Timestamp of when the balance was created."),
    ] = None
    expires_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="expiresAt"),
        pydantic.Field(alias="expiresAt", description="Expiration timestamp of the balance."),
    ] = None
    consumed_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="consumedAt"),
        pydantic.Field(alias="consumedAt", description="Timestamp of when the balance was last consumed."),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
