# This file was auto-generated by Fern from our API Definition.

import typing

UpdateBalanceDefinitionRequestBalanceAvailabilityDurationModifier = typing.Union[
    typing.Literal["noModification", "startOfPeriod", "endOfPeriod"], typing.Any
]
