# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from ...core.unchecked_base_model import UncheckedBaseModel
from .get_corporate_sub_account_id_response_plan_info_features_inbox import (
    GetCorporateSubAccountIdResponsePlanInfoFeaturesInbox,
)
from .get_corporate_sub_account_id_response_plan_info_features_landing_page import (
    GetCorporateSubAccountIdResponsePlanInfoFeaturesLandingPage,
)
from .get_corporate_sub_account_id_response_plan_info_features_sales_users import (
    GetCorporateSubAccountIdResponsePlanInfoFeaturesSalesUsers,
)
from .get_corporate_sub_account_id_response_plan_info_features_users import (
    GetCorporateSubAccountIdResponsePlanInfoFeaturesUsers,
)


class GetCorporateSubAccountIdResponsePlanInfoFeatures(UncheckedBaseModel):
    """
    Features available on the sub-account
    """

    inbox: typing.Optional[GetCorporateSubAccountIdResponsePlanInfoFeaturesInbox] = pydantic.Field(default=None)
    """
    Inbox details / Not applicable on ENTv2
    """

    landing_page: typing_extensions.Annotated[
        typing.Optional[GetCorporateSubAccountIdResponsePlanInfoFeaturesLandingPage],
        FieldMetadata(alias="landingPage"),
        pydantic.Field(alias="landingPage", description="Landing page details / Not applicable on ENTv2"),
    ] = None
    sales_users: typing_extensions.Annotated[
        typing.Optional[GetCorporateSubAccountIdResponsePlanInfoFeaturesSalesUsers],
        FieldMetadata(alias="salesUsers"),
        pydantic.Field(
            alias="salesUsers", description="Sales and service users to use phone, sales and\nconversations"
        ),
    ] = None
    users: typing.Optional[GetCorporateSubAccountIdResponsePlanInfoFeaturesUsers] = pydantic.Field(default=None)
    """
    Marketing users to manage the marketing channels
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
