# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from ...core.unchecked_base_model import UncheckedBaseModel
from .get_corporate_master_account_response_billing_info import GetCorporateMasterAccountResponseBillingInfo
from .get_corporate_master_account_response_plan_info import GetCorporateMasterAccountResponsePlanInfo


class GetCorporateMasterAccountResponse(UncheckedBaseModel):
    billing_info: typing_extensions.Annotated[
        typing.Optional[GetCorporateMasterAccountResponseBillingInfo],
        FieldMetadata(alias="billingInfo"),
        pydantic.Field(alias="billingInfo", description="Billing details of the master account organization"),
    ] = None
    company_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="companyName"),
        pydantic.Field(alias="companyName", description="Company name of master account organization"),
    ] = None
    currency_code: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="currencyCode"),
        pydantic.Field(alias="currencyCode", description="Currency code of the master account organization"),
    ] = None
    email: typing.Optional[str] = pydantic.Field(default=None)
    """
    Email id of master account
    """

    id: typing.Optional[int] = pydantic.Field(default=None)
    """
    Unique identifier of the master account organization
    """

    plan_info: typing_extensions.Annotated[
        typing.Optional[GetCorporateMasterAccountResponsePlanInfo],
        FieldMetadata(alias="planInfo"),
        pydantic.Field(alias="planInfo", description="Plan details"),
    ] = None
    timezone: typing.Optional[str] = pydantic.Field(default=None)
    """
    Timezone of the master account organization
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
