# This file was auto-generated by Fern from our API Definition.

import typing

PostCorporateSubAccountSsoTokenRequestTarget = typing.Union[
    typing.Literal[
        "automation",
        "email_campaign",
        "contacts",
        "landing_pages",
        "email_transactional",
        "senders",
        "sms_campaign",
        "sms_transactional",
    ],
    typing.Any,
]
