# This file was auto-generated by Fern from our API Definition.

import typing

CreateAttributeRequestType = typing.Union[
    typing.Literal["text", "date", "float", "boolean", "id", "category", "multiple-choice", "user"], typing.Any
]
