# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from ...core.unchecked_base_model import UncheckedBaseModel
from .get_contact_info_response_statistics_clicked_item import GetContactInfoResponseStatisticsClickedItem
from .get_contact_info_response_statistics_complaints_item import GetContactInfoResponseStatisticsComplaintsItem
from .get_contact_info_response_statistics_delivered_item import GetContactInfoResponseStatisticsDeliveredItem
from .get_contact_info_response_statistics_hard_bounces_item import GetContactInfoResponseStatisticsHardBouncesItem
from .get_contact_info_response_statistics_messages_sent_item import GetContactInfoResponseStatisticsMessagesSentItem
from .get_contact_info_response_statistics_opened_item import GetContactInfoResponseStatisticsOpenedItem
from .get_contact_info_response_statistics_soft_bounces_item import GetContactInfoResponseStatisticsSoftBouncesItem
from .get_contact_info_response_statistics_transac_attributes_item import (
    GetContactInfoResponseStatisticsTransacAttributesItem,
)
from .get_contact_info_response_statistics_unsubscriptions import GetContactInfoResponseStatisticsUnsubscriptions


class GetContactInfoResponseStatistics(UncheckedBaseModel):
    """
    Campaign statistics of the contact
    """

    clicked: typing.Optional[typing.List[GetContactInfoResponseStatisticsClickedItem]] = pydantic.Field(default=None)
    """
    Listing of the clicks generated by the contact
    """

    complaints: typing.Optional[typing.List[GetContactInfoResponseStatisticsComplaintsItem]] = pydantic.Field(
        default=None
    )
    """
    Listing of the complaints generated by the contact
    """

    delivered: typing.Optional[typing.List[GetContactInfoResponseStatisticsDeliveredItem]] = pydantic.Field(
        default=None
    )
    """
    Listing of the delivered campaign for the contact
    """

    hard_bounces: typing_extensions.Annotated[
        typing.Optional[typing.List[GetContactInfoResponseStatisticsHardBouncesItem]],
        FieldMetadata(alias="hardBounces"),
        pydantic.Field(alias="hardBounces", description="Listing of the hardbounes generated by the contact"),
    ] = None
    messages_sent: typing_extensions.Annotated[
        typing.Optional[typing.List[GetContactInfoResponseStatisticsMessagesSentItem]],
        FieldMetadata(alias="messagesSent"),
        pydantic.Field(alias="messagesSent", description="Listing of the sent campaign for the contact"),
    ] = None
    opened: typing.Optional[typing.List[GetContactInfoResponseStatisticsOpenedItem]] = pydantic.Field(default=None)
    """
    Listing of the openings generated by the contact
    """

    soft_bounces: typing_extensions.Annotated[
        typing.Optional[typing.List[GetContactInfoResponseStatisticsSoftBouncesItem]],
        FieldMetadata(alias="softBounces"),
        pydantic.Field(alias="softBounces", description="Listing of the softbounes generated by the contact"),
    ] = None
    transac_attributes: typing_extensions.Annotated[
        typing.Optional[typing.List[GetContactInfoResponseStatisticsTransacAttributesItem]],
        FieldMetadata(alias="transacAttributes"),
        pydantic.Field(
            alias="transacAttributes", description="Listing of the transactional attributes for the contact"
        ),
    ] = None
    unsubscriptions: typing.Optional[GetContactInfoResponseStatisticsUnsubscriptions] = pydantic.Field(default=None)
    """
    Listing of the unsubscription for the contact
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
