# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from ...core.unchecked_base_model import UncheckedBaseModel
from .get_contact_info_response_statistics_unsubscriptions_admin_unsubscription_item import (
    GetContactInfoResponseStatisticsUnsubscriptionsAdminUnsubscriptionItem,
)
from .get_contact_info_response_statistics_unsubscriptions_user_unsubscription_item import (
    GetContactInfoResponseStatisticsUnsubscriptionsUserUnsubscriptionItem,
)


class GetContactInfoResponseStatisticsUnsubscriptions(UncheckedBaseModel):
    """
    Listing of the unsubscription for the contact
    """

    admin_unsubscription: typing_extensions.Annotated[
        typing.List[GetContactInfoResponseStatisticsUnsubscriptionsAdminUnsubscriptionItem],
        FieldMetadata(alias="adminUnsubscription"),
        pydantic.Field(alias="adminUnsubscription", description="Contact has been unsubscribed from the administrator"),
    ]
    user_unsubscription: typing_extensions.Annotated[
        typing.List[GetContactInfoResponseStatisticsUnsubscriptionsUserUnsubscriptionItem],
        FieldMetadata(alias="userUnsubscription"),
        pydantic.Field(
            alias="userUnsubscription", description="Contact unsubscribe via unsubscription link in a campaign"
        ),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
