# This file was auto-generated by Fern from our API Definition.

import typing

from .remove_contact_from_list_request_body_all import RemoveContactFromListRequestBodyAll
from .remove_contact_from_list_request_body_emails import RemoveContactFromListRequestBodyEmails
from .remove_contact_from_list_request_body_ext_ids import RemoveContactFromListRequestBodyExtIds
from .remove_contact_from_list_request_body_ids import RemoveContactFromListRequestBodyIds

RemoveContactFromListRequestBody = typing.Union[
    RemoveContactFromListRequestBodyEmails,
    RemoveContactFromListRequestBodyIds,
    RemoveContactFromListRequestBodyAll,
    RemoveContactFromListRequestBodyExtIds,
]
