# This file was auto-generated by Fern from our API Definition.

import typing

UpdateAttributeRequestAttributeCategory = typing.Union[
    typing.Literal["category", "calculated", "global", "normal"], typing.Any
]
