# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.cart import Cart
from ..types.configuration import Configuration
from ..types.notification import Notification
from .raw_client import AsyncRawPaymentsClient, RawPaymentsClient
from .types.create_payment_request_response import CreatePaymentRequestResponse
from .types.get_payment_request_response import GetPaymentRequestResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class PaymentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPaymentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPaymentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPaymentsClient
        """
        return self._raw_client

    def create_payment_request(
        self,
        *,
        cart: Cart,
        contact_id: int,
        reference: str,
        configuration: typing.Optional[Configuration] = OMIT,
        description: typing.Optional[str] = OMIT,
        notification: typing.Optional[Notification] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreatePaymentRequestResponse:
        """
        Parameters
        ----------
        cart : Cart

        contact_id : int
            Brevo ID of the contact requested to pay.

        reference : str
            Reference of the payment request, it will appear on the payment page.

        configuration : typing.Optional[Configuration]

        description : typing.Optional[str]
            Description of payment request.

        notification : typing.Optional[Notification]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatePaymentRequestResponse
            Payment request created.

        Examples
        --------
        from brevo import Brevo, Cart

        client = Brevo(
            api_key="YOUR_API_KEY",
        )
        client.payments.create_payment_request(
            cart=Cart(
                specific_amount=1200,
            ),
            contact_id=43,
            reference="Invoice #INV0001",
        )
        """
        _response = self._raw_client.create_payment_request(
            cart=cart,
            contact_id=contact_id,
            reference=reference,
            configuration=configuration,
            description=description,
            notification=notification,
            request_options=request_options,
        )
        return _response.data

    def get_payment_request(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetPaymentRequestResponse:
        """
        Parameters
        ----------
        id : str
            Id of the payment Request

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPaymentRequestResponse
            Payment request details

        Examples
        --------
        from brevo import Brevo

        client = Brevo(
            api_key="YOUR_API_KEY",
        )
        client.payments.get_payment_request(
            id="050db7b0-9bb7-4c1e-9c68-5a8dace8c1dc",
        )
        """
        _response = self._raw_client.get_payment_request(id, request_options=request_options)
        return _response.data

    def delete_payment_request(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        id : str
            ID of the payment request.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from brevo import Brevo

        client = Brevo(
            api_key="YOUR_API_KEY",
        )
        client.payments.delete_payment_request(
            id="9ae7d68a-565c-4695-9381-d8fb3e3a14cc",
        )
        """
        _response = self._raw_client.delete_payment_request(id, request_options=request_options)
        return _response.data


class AsyncPaymentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPaymentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPaymentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPaymentsClient
        """
        return self._raw_client

    async def create_payment_request(
        self,
        *,
        cart: Cart,
        contact_id: int,
        reference: str,
        configuration: typing.Optional[Configuration] = OMIT,
        description: typing.Optional[str] = OMIT,
        notification: typing.Optional[Notification] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreatePaymentRequestResponse:
        """
        Parameters
        ----------
        cart : Cart

        contact_id : int
            Brevo ID of the contact requested to pay.

        reference : str
            Reference of the payment request, it will appear on the payment page.

        configuration : typing.Optional[Configuration]

        description : typing.Optional[str]
            Description of payment request.

        notification : typing.Optional[Notification]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatePaymentRequestResponse
            Payment request created.

        Examples
        --------
        import asyncio

        from brevo import AsyncBrevo, Cart

        client = AsyncBrevo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.payments.create_payment_request(
                cart=Cart(
                    specific_amount=1200,
                ),
                contact_id=43,
                reference="Invoice #INV0001",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_payment_request(
            cart=cart,
            contact_id=contact_id,
            reference=reference,
            configuration=configuration,
            description=description,
            notification=notification,
            request_options=request_options,
        )
        return _response.data

    async def get_payment_request(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetPaymentRequestResponse:
        """
        Parameters
        ----------
        id : str
            Id of the payment Request

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPaymentRequestResponse
            Payment request details

        Examples
        --------
        import asyncio

        from brevo import AsyncBrevo

        client = AsyncBrevo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.payments.get_payment_request(
                id="050db7b0-9bb7-4c1e-9c68-5a8dace8c1dc",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_payment_request(id, request_options=request_options)
        return _response.data

    async def delete_payment_request(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        id : str
            ID of the payment request.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from brevo import AsyncBrevo

        client = AsyncBrevo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.payments.delete_payment_request(
                id="9ae7d68a-565c-4695-9381-d8fb3e3a14cc",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_payment_request(id, request_options=request_options)
        return _response.data
