# This file was auto-generated by Fern from our API Definition.

import typing

from .. import core
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.file_data import FileData
from .raw_client import AsyncRawFilesClient, RawFilesClient
from .types.get_crm_files_id_response import GetCrmFilesIdResponse
from .types.get_crm_files_request_entity import GetCrmFilesRequestEntity
from .types.get_crm_files_request_sort import GetCrmFilesRequestSort

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class FilesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawFilesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawFilesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawFilesClient
        """
        return self._raw_client

    def get_all_files(
        self,
        *,
        entity: typing.Optional[GetCrmFilesRequestEntity] = None,
        entity_ids: typing.Optional[str] = None,
        date_from: typing.Optional[int] = None,
        date_to: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        sort: typing.Optional[GetCrmFilesRequestSort] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[FileData]:
        """
        Parameters
        ----------
        entity : typing.Optional[GetCrmFilesRequestEntity]
            Filter by file entity type

        entity_ids : typing.Optional[str]
            Filter by file entity IDs

        date_from : typing.Optional[int]
            dateFrom to date range filter type (timestamp in milliseconds)

        date_to : typing.Optional[int]
            dateTo to date range filter type (timestamp in milliseconds)

        offset : typing.Optional[int]
            Index of the first document of the page

        limit : typing.Optional[int]
            Number of documents per page

        sort : typing.Optional[GetCrmFilesRequestSort]
            Sort the results in the ascending/descending order. Default order is **descending** by creation if `sort` is not passed

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[FileData]
            Returns files list with filters

        Examples
        --------
        from brevo import Brevo

        client = Brevo(
            api_key="YOUR_API_KEY",
        )
        client.files.get_all_files()
        """
        _response = self._raw_client.get_all_files(
            entity=entity,
            entity_ids=entity_ids,
            date_from=date_from,
            date_to=date_to,
            offset=offset,
            limit=limit,
            sort=sort,
            request_options=request_options,
        )
        return _response.data

    def upload_a_file(
        self,
        *,
        file: core.File,
        company_id: typing.Optional[str] = OMIT,
        contact_id: typing.Optional[int] = OMIT,
        deal_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FileData:
        """
        Parameters
        ----------
        file : core.File
            See core.File for more documentation

        company_id : typing.Optional[str]

        contact_id : typing.Optional[int]

        deal_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileData
            Returns the created File with additional details

        Examples
        --------
        from brevo import Brevo

        client = Brevo(
            api_key="YOUR_API_KEY",
        )
        client.files.upload_a_file()
        """
        _response = self._raw_client.upload_a_file(
            file=file, company_id=company_id, contact_id=contact_id, deal_id=deal_id, request_options=request_options
        )
        return _response.data

    def download_a_file(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetCrmFilesIdResponse:
        """
        Parameters
        ----------
        id : str
            File id to download.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetCrmFilesIdResponse
            Returns downloadable file link. Valid for next 5 minutes only.

        Examples
        --------
        from brevo import Brevo

        client = Brevo(
            api_key="YOUR_API_KEY",
        )
        client.files.download_a_file(
            id="id",
        )
        """
        _response = self._raw_client.download_a_file(id, request_options=request_options)
        return _response.data

    def delete_a_file(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        id : str
            File id to delete.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from brevo import Brevo

        client = Brevo(
            api_key="YOUR_API_KEY",
        )
        client.files.delete_a_file(
            id="id",
        )
        """
        _response = self._raw_client.delete_a_file(id, request_options=request_options)
        return _response.data

    def get_file_details(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> FileData:
        """
        Parameters
        ----------
        id : str
            File id to get file data.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileData
            Returned when file is found.

        Examples
        --------
        from brevo import Brevo

        client = Brevo(
            api_key="YOUR_API_KEY",
        )
        client.files.get_file_details(
            id="id",
        )
        """
        _response = self._raw_client.get_file_details(id, request_options=request_options)
        return _response.data


class AsyncFilesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawFilesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawFilesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawFilesClient
        """
        return self._raw_client

    async def get_all_files(
        self,
        *,
        entity: typing.Optional[GetCrmFilesRequestEntity] = None,
        entity_ids: typing.Optional[str] = None,
        date_from: typing.Optional[int] = None,
        date_to: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        sort: typing.Optional[GetCrmFilesRequestSort] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[FileData]:
        """
        Parameters
        ----------
        entity : typing.Optional[GetCrmFilesRequestEntity]
            Filter by file entity type

        entity_ids : typing.Optional[str]
            Filter by file entity IDs

        date_from : typing.Optional[int]
            dateFrom to date range filter type (timestamp in milliseconds)

        date_to : typing.Optional[int]
            dateTo to date range filter type (timestamp in milliseconds)

        offset : typing.Optional[int]
            Index of the first document of the page

        limit : typing.Optional[int]
            Number of documents per page

        sort : typing.Optional[GetCrmFilesRequestSort]
            Sort the results in the ascending/descending order. Default order is **descending** by creation if `sort` is not passed

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[FileData]
            Returns files list with filters

        Examples
        --------
        import asyncio

        from brevo import AsyncBrevo

        client = AsyncBrevo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.files.get_all_files()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_all_files(
            entity=entity,
            entity_ids=entity_ids,
            date_from=date_from,
            date_to=date_to,
            offset=offset,
            limit=limit,
            sort=sort,
            request_options=request_options,
        )
        return _response.data

    async def upload_a_file(
        self,
        *,
        file: core.File,
        company_id: typing.Optional[str] = OMIT,
        contact_id: typing.Optional[int] = OMIT,
        deal_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FileData:
        """
        Parameters
        ----------
        file : core.File
            See core.File for more documentation

        company_id : typing.Optional[str]

        contact_id : typing.Optional[int]

        deal_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileData
            Returns the created File with additional details

        Examples
        --------
        import asyncio

        from brevo import AsyncBrevo

        client = AsyncBrevo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.files.upload_a_file()


        asyncio.run(main())
        """
        _response = await self._raw_client.upload_a_file(
            file=file, company_id=company_id, contact_id=contact_id, deal_id=deal_id, request_options=request_options
        )
        return _response.data

    async def download_a_file(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetCrmFilesIdResponse:
        """
        Parameters
        ----------
        id : str
            File id to download.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetCrmFilesIdResponse
            Returns downloadable file link. Valid for next 5 minutes only.

        Examples
        --------
        import asyncio

        from brevo import AsyncBrevo

        client = AsyncBrevo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.files.download_a_file(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.download_a_file(id, request_options=request_options)
        return _response.data

    async def delete_a_file(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        id : str
            File id to delete.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from brevo import AsyncBrevo

        client = AsyncBrevo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.files.delete_a_file(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_a_file(id, request_options=request_options)
        return _response.data

    async def get_file_details(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> FileData:
        """
        Parameters
        ----------
        id : str
            File id to get file data.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileData
            Returned when file is found.

        Examples
        --------
        import asyncio

        from brevo import AsyncBrevo

        client = AsyncBrevo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.files.get_file_details(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_file_details(id, request_options=request_options)
        return _response.data
