# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from ...core.unchecked_base_model import UncheckedBaseModel


class RedeemVoucherRequestOrderBilling(UncheckedBaseModel):
    address: typing.Optional[str] = pydantic.Field(default=None)
    """
    Address of the user
    """

    city: typing.Optional[str] = pydantic.Field(default=None)
    """
    City of the user
    """

    country_code: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="countryCode"),
        pydantic.Field(alias="countryCode", description="Country code of the user"),
    ] = None
    payment_method: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="paymentMethod"),
        pydantic.Field(alias="paymentMethod", description="Payment method opted by the user"),
    ] = None
    phone: typing.Optional[int] = pydantic.Field(default=None)
    """
    Phone number of the user
    """

    post_code: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="postCode"),
        pydantic.Field(alias="postCode", description="Postal Code of user's location"),
    ] = None
    region: typing.Optional[str] = pydantic.Field(default=None)
    """
    Region where user resides
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
