# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .balance_definition_balance_availability_duration_modifier import (
    BalanceDefinitionBalanceAvailabilityDurationModifier,
)
from .balance_definition_balance_availability_duration_unit import BalanceDefinitionBalanceAvailabilityDurationUnit
from .balance_definition_balance_option_amount_overtaking_strategy import (
    BalanceDefinitionBalanceOptionAmountOvertakingStrategy,
)
from .balance_definition_balance_option_credit_rounding import BalanceDefinitionBalanceOptionCreditRounding
from .balance_definition_balance_option_debit_rounding import BalanceDefinitionBalanceOptionDebitRounding
from .balance_definition_unit import BalanceDefinitionUnit


class BalanceDefinition(UncheckedBaseModel):
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique identifier for the balance definition.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the balance definition.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Short description of the balance definition.
    """

    image_ref: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="imageRef"),
        pydantic.Field(alias="imageRef", description="Optional image reference URL."),
    ] = None
    meta: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Additional metadata for the balance definition.
    """

    unit: typing.Optional[BalanceDefinitionUnit] = pydantic.Field(default=None)
    """
    Unit of balance measurement.
    """

    min_amount: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="minAmount"),
        pydantic.Field(alias="minAmount", description="Minimum allowable balance."),
    ] = None
    max_amount: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="maxAmount"),
        pydantic.Field(alias="maxAmount", description="Maximum allowable balance."),
    ] = None
    max_credit_amount_limit: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="maxCreditAmountLimit"),
        pydantic.Field(alias="maxCreditAmountLimit", description="Maximum credit allowed per operation."),
    ] = None
    max_debit_amount_limit: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="maxDebitAmountLimit"),
        pydantic.Field(alias="maxDebitAmountLimit", description="Maximum debit allowed per operation."),
    ] = None
    balance_option_amount_overtaking_strategy: typing_extensions.Annotated[
        typing.Optional[BalanceDefinitionBalanceOptionAmountOvertakingStrategy],
        FieldMetadata(alias="balanceOptionAmountOvertakingStrategy"),
        pydantic.Field(
            alias="balanceOptionAmountOvertakingStrategy",
            description="Partial enables partial credit of balance if maximum balance limit is reached. Strict enables rejection of a transaction if it will breach the max balance limit.",
        ),
    ] = None
    balance_option_credit_rounding: typing_extensions.Annotated[
        typing.Optional[BalanceDefinitionBalanceOptionCreditRounding],
        FieldMetadata(alias="balanceOptionCreditRounding"),
        pydantic.Field(alias="balanceOptionCreditRounding", description="Rounding strategy for credit transactions."),
    ] = None
    balance_option_debit_rounding: typing_extensions.Annotated[
        typing.Optional[BalanceDefinitionBalanceOptionDebitRounding],
        FieldMetadata(alias="balanceOptionDebitRounding"),
        pydantic.Field(alias="balanceOptionDebitRounding", description="Rounding strategy for debit transactions."),
    ] = None
    balance_availability_duration_value: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="balanceAvailabilityDurationValue"),
        pydantic.Field(
            alias="balanceAvailabilityDurationValue", description="Number of time units before the balance expires."
        ),
    ] = None
    balance_availability_duration_unit: typing_extensions.Annotated[
        typing.Optional[BalanceDefinitionBalanceAvailabilityDurationUnit],
        FieldMetadata(alias="balanceAvailabilityDurationUnit"),
        pydantic.Field(
            alias="balanceAvailabilityDurationUnit", description="Unit of time for the balance availability duration."
        ),
    ] = None
    balance_availability_duration_modifier: typing_extensions.Annotated[
        typing.Optional[BalanceDefinitionBalanceAvailabilityDurationModifier],
        FieldMetadata(alias="balanceAvailabilityDurationModifier"),
        pydantic.Field(
            alias="balanceAvailabilityDurationModifier",
            description="Modifier for balance availability duration. startOfPeriod causes expiry at the start of the period, endOfPeriod at the end. noModification uses the exact duration from the credit date.",
        ),
    ] = None
    balance_expiration_date: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="balanceExpirationDate"),
        pydantic.Field(
            alias="balanceExpirationDate",
            description="Fixed expiration date in dd/mm format. The balance expires when this date next appears in the calendar. Only one of balanceExpirationDate or balance availability duration fields can be used.",
        ),
    ] = None
    created_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="Timestamp of balance definition creation."),
    ] = None
    updated_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="updatedAt"),
        pydantic.Field(alias="updatedAt", description="Timestamp of the last update."),
    ] = None
    deleted_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="deletedAt"),
        pydantic.Field(alias="deletedAt", description="Timestamp of balance definition deletion (nullable)."),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
