# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class BalanceLimit(UncheckedBaseModel):
    balance_definition_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="balanceDefinitionId"),
        pydantic.Field(alias="balanceDefinitionId", description="balance definition ID"),
    ] = None
    constraint_type: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="constraintType"),
        pydantic.Field(
            alias="constraintType",
            description="Defines the type of constraint (e.g., transaction-based or amount-based).",
        ),
    ] = None
    created_at: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="Timestamp of when the balance limit was created."),
    ]
    duration_unit: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="durationUnit"),
        pydantic.Field(alias="durationUnit", description="Time unit for the balance limit (day, week, month, year)."),
    ] = None
    duration_value: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="durationValue"),
        pydantic.Field(alias="durationValue", description="Number of time units the balance limit applies to."),
    ] = None
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique identifier for the balance limit.
    """

    sliding_schedule: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="slidingSchedule"),
        pydantic.Field(
            alias="slidingSchedule",
            description="Indicates if the limit resets periodically based on a sliding schedule.",
        ),
    ] = None
    transaction_type: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="transactionType"),
        pydantic.Field(
            alias="transactionType", description="Specifies whether the limit applies to credit or debit transactions."
        ),
    ] = None
    updated_at: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="updatedAt"),
        pydantic.Field(alias="updatedAt", description="Timestamp of the last update to the balance limit."),
    ]
    value: typing.Optional[int] = pydantic.Field(default=None)
    """
    The maximum allowed value for the defined constraint.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
