# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class ConversationsMessageAttachmentsItemImageInfo(UncheckedBaseModel):
    """
    Image information (only present for image files).
    """

    width: typing.Optional[int] = pydantic.Field(default=None)
    """
    Width of the image in pixels.
    """

    height: typing.Optional[int] = pydantic.Field(default=None)
    """
    Height of the image in pixels.
    """

    preview_link: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="previewLink"),
        pydantic.Field(alias="previewLink", description="URL of the image preview."),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
