# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class GetCampaignStats(UncheckedBaseModel):
    apple_mpp_opens: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="appleMppOpens"),
        pydantic.Field(
            alias="appleMppOpens",
            description="Numbers of times your email has been opened automatically through Apple MPP.",
        ),
    ] = None
    clickers: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of total clicks for the campaign
    """

    complaints: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of complaints (Spam reports) for the campaign
    """

    deferred: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of deferred emails for the campaign
    """

    delivered: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of delivered emails for the campaign
    """

    estimated_views: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="estimatedViews"),
        pydantic.Field(
            alias="estimatedViews",
            description="Rate of recipients without any privacy protection option enabled in their email client, applied to all delivered emails",
        ),
    ] = None
    hard_bounces: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="hardBounces"),
        pydantic.Field(alias="hardBounces", description="Number of hard bounces for the campaign"),
    ] = None
    list_id: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="listId"),
        pydantic.Field(
            alias="listId",
            description="List Id of email campaign (only in case of get email campaign(s)(not for global stats))",
        ),
    ] = None
    opens_rate: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="opensRate"),
        pydantic.Field(
            alias="opensRate",
            description="Percentage of recipients who open the email out of your total number of recipients. Depending on your Campaign settings, they may include Apple MPP opens.",
        ),
    ] = None
    return_bounce: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="returnBounce"),
        pydantic.Field(
            alias="returnBounce", description="Total number of non-delivered campaigns for a particular campaign id."
        ),
    ] = None
    sent: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of sent emails for the campaign
    """

    soft_bounces: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="softBounces"),
        pydantic.Field(alias="softBounces", description="Number of softbounce for the campaign"),
    ] = None
    trackable_views: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="trackableViews"),
        pydantic.Field(
            alias="trackableViews",
            description="Recipients without any privacy protection option enabled in their email email client",
        ),
    ] = None
    trackable_views_rate: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="trackableViewsRate"),
        pydantic.Field(
            alias="trackableViewsRate",
            description="Rate of recipients without any privacy protection option enabled in their email client",
        ),
    ] = None
    unique_clicks: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="uniqueClicks"),
        pydantic.Field(alias="uniqueClicks", description="Number of unique clicks for the campaign"),
    ] = None
    unique_views: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="uniqueViews"),
        pydantic.Field(alias="uniqueViews", description="Number of unique openings for the campaign"),
    ] = None
    unsubscriptions: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of unsubscription for the campaign
    """

    viewed: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of openings for the campaign
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
