# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class GetFolder(UncheckedBaseModel):
    id: int = pydantic.Field()
    """
    ID of the folder
    """

    name: str = pydantic.Field()
    """
    Name of the folder
    """

    total_blacklisted: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="totalBlacklisted"),
        pydantic.Field(alias="totalBlacklisted", description="Number of blacklisted contacts in the folder"),
    ]
    total_subscribers: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="totalSubscribers"),
        pydantic.Field(alias="totalSubscribers", description="Number of contacts in the folder"),
    ]
    unique_subscribers: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="uniqueSubscribers"),
        pydantic.Field(alias="uniqueSubscribers", description="Number of unique contacts in the folder"),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
