# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class GetCategoryDetails(UncheckedBaseModel):
    created_at: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="createdAt"),
        pydantic.Field(
            alias="createdAt", description="Creation UTC date-time of the category (YYYY-MM-DDTHH:mm:ss.SSSZ)"
        ),
    ]
    id: str = pydantic.Field()
    """
    Category ID for which you requested the details
    """

    is_deleted: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="isDeleted"),
        pydantic.Field(alias="isDeleted", description="category deleted from the shop's database"),
    ]
    modified_at: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="modifiedAt"),
        pydantic.Field(
            alias="modifiedAt", description="Last modification UTC date-time of the category (YYYY-MM-DDTHH:mm:ss.SSSZ)"
        ),
    ]
    name: str = pydantic.Field()
    """
    Name of the category for which you requested the details
    """

    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    URL to the category
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
