# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class OrderProductsItemQuantityFloat(UncheckedBaseModel):
    quantity_float: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="quantityFloat"),
        pydantic.Field(
            alias="quantityFloat",
            description="**Required if quantity is empty.** Number of product units added to the cart(supports decimals)",
        ),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
