# This file was auto-generated by Fern from our API Definition.

import typing

TransactionStatus = typing.Union[typing.Literal["pending", "complete", "rejected", "cancelled", "expired"], typing.Any]
