# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_event_request_contact_properties_value import CreateEventRequestContactPropertiesValue
    from .create_event_request_event_properties_value import CreateEventRequestEventPropertiesValue
    from .create_event_request_identifiers import CreateEventRequestIdentifiers
    from .create_event_request_object import CreateEventRequestObject
    from .create_event_request_object_identifiers import CreateEventRequestObjectIdentifiers
_dynamic_imports: typing.Dict[str, str] = {
    "CreateEventRequestContactPropertiesValue": ".create_event_request_contact_properties_value",
    "CreateEventRequestEventPropertiesValue": ".create_event_request_event_properties_value",
    "CreateEventRequestIdentifiers": ".create_event_request_identifiers",
    "CreateEventRequestObject": ".create_event_request_object",
    "CreateEventRequestObjectIdentifiers": ".create_event_request_object_identifiers",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateEventRequestContactPropertiesValue",
    "CreateEventRequestEventPropertiesValue",
    "CreateEventRequestIdentifiers",
    "CreateEventRequestObject",
    "CreateEventRequestObjectIdentifiers",
]
