# This file was auto-generated by Fern from our API Definition.

import typing

CreateBatchEventsRequestItemEventPropertiesValue = typing.Union[
    str, int, typing.Dict[str, typing.Any], typing.List[typing.Any]
]
