# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.get_sso_token import GetSsoToken
from .raw_client import AsyncRawMasterAccountClient, RawMasterAccountClient
from .types.get_corporate_group_id_response import GetCorporateGroupIdResponse
from .types.get_corporate_invited_users_list_response import GetCorporateInvitedUsersListResponse
from .types.get_corporate_ip_response_item import GetCorporateIpResponseItem
from .types.get_corporate_master_account_response import GetCorporateMasterAccountResponse
from .types.get_corporate_sub_account_id_response import GetCorporateSubAccountIdResponse
from .types.get_corporate_sub_account_response import GetCorporateSubAccountResponse
from .types.get_corporate_user_permission_response import GetCorporateUserPermissionResponse
from .types.get_sub_account_groups_response_item import GetSubAccountGroupsResponseItem
from .types.invite_admin_user_request_privileges_item import InviteAdminUserRequestPrivilegesItem
from .types.invite_admin_user_response import InviteAdminUserResponse
from .types.post_corporate_group_response import PostCorporateGroupResponse
from .types.post_corporate_sub_account_key_response import PostCorporateSubAccountKeyResponse
from .types.post_corporate_sub_account_request_language import PostCorporateSubAccountRequestLanguage
from .types.post_corporate_sub_account_response import PostCorporateSubAccountResponse
from .types.post_corporate_sub_account_sso_token_request_target import PostCorporateSubAccountSsoTokenRequestTarget
from .types.put_corporate_sub_account_id_plan_request_credits import PutCorporateSubAccountIdPlanRequestCredits
from .types.put_corporate_sub_account_id_plan_request_features import PutCorporateSubAccountIdPlanRequestFeatures
from .types.put_corporate_sub_accounts_plan_request_credits import PutCorporateSubAccountsPlanRequestCredits
from .types.put_corporate_sub_accounts_plan_request_features import PutCorporateSubAccountsPlanRequestFeatures
from .types.put_corporate_user_email_permissions_request_privileges_item import (
    PutCorporateUserEmailPermissionsRequestPrivilegesItem,
)
from .types.put_corporate_user_invitation_action_email_request_action import (
    PutCorporateUserInvitationActionEmailRequestAction,
)
from .types.put_corporate_user_invitation_action_email_response import PutCorporateUserInvitationActionEmailResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class MasterAccountClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMasterAccountClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMasterAccountClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMasterAccountClient
        """
        return self._raw_client

    def create_a_new_group_of_sub_accounts(
        self,
        *,
        group_name: str,
        sub_account_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostCorporateGroupResponse:
        """
        This endpoint allows to create a group of sub-accounts

        Parameters
        ----------
        group_name : str
            The name of the group of sub-accounts

        sub_account_ids : typing.Optional[typing.Sequence[int]]
            Pass the list of sub-account Ids to be included in the group

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostCorporateGroupResponse
            Group ID

        Examples
        --------
        from brevo import Brevo

        client = Brevo(
            api_key="YOUR_API_KEY",
        )
        client.master_account.create_a_new_group_of_sub_accounts(
            group_name="My group",
        )
        """
        _response = self._raw_client.create_a_new_group_of_sub_accounts(
            group_name=group_name, sub_account_ids=sub_account_ids, request_options=request_options
        )
        return _response.data

    def delete_sub_account_from_group(
        self,
        group_id: str,
        *,
        sub_account_ids: typing.Sequence[int],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        This endpoint allows you to remove a sub-organization from a group.

        Parameters
        ----------
        group_id : str
            Group id

        sub_account_ids : typing.Sequence[int]
            List of sub-account ids

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from brevo import Brevo

        client = Brevo(
            api_key="YOUR_API_KEY",
        )
        client.master_account.delete_sub_account_from_group(
            group_id="groupId",
            sub_account_ids=[423432, 234323, 87678],
        )
        """
        _response = self._raw_client.delete_sub_account_from_group(
            group_id, sub_account_ids=sub_account_ids, request_options=request_options
        )
        return _response.data

    def get_a_group_details(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetCorporateGroupIdResponse:
        """
        This endpoint allows you to retrieve a specific group’s information such as
        the list of sub-organizations and the user associated with the group.

        Parameters
        ----------
        id : str
            Id of the group of sub-organization

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetCorporateGroupIdResponse
            Group details

        Examples
        --------
        from brevo import Brevo

        client = Brevo(
            api_key="YOUR_API_KEY",
        )
        client.master_account.get_a_group_details(
            id="id",
        )
        """
        _response = self._raw_client.get_a_group_details(id, request_options=request_options)
        return _response.data

    def update_a_group_of_sub_accounts(
        self,
        id: str,
        *,
        group_name: typing.Optional[str] = OMIT,
        sub_account_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        This endpoint allows to update a group of sub-accounts

        Parameters
        ----------
        id : str
            Id of the group

        group_name : typing.Optional[str]
            The name of the group of sub-accounts

        sub_account_ids : typing.Optional[typing.Sequence[int]]
            Pass the list of sub-account Ids to be included in the group

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from brevo import Brevo

        client = Brevo(
            api_key="YOUR_API_KEY",
        )
        client.master_account.update_a_group_of_sub_accounts(
            id="id",
        )
        """
        _response = self._raw_client.update_a_group_of_sub_accounts(
            id, group_name=group_name, sub_account_ids=sub_account_ids, request_options=request_options
        )
        return _response.data

    def delete_a_group(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        This endpoint allows you to delete a group of sub-organizations. When a
        group is deleted, the sub-organizations are no longer part of this group.
        The users associated with the group are no longer associated with the group
        once deleted.

        Parameters
        ----------
        id : str
            Id of the group

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from brevo import Brevo

        client = Brevo(
            api_key="YOUR_API_KEY",
        )
        client.master_account.delete_a_group(
            id="id",
        )
        """
        _response = self._raw_client.delete_a_group(id, request_options=request_options)
        return _response.data

    def get_sub_account_groups(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[GetSubAccountGroupsResponseItem]:
        """
        This endpoint allows you to list all groups created on your Admin account.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[GetSubAccountGroupsResponseItem]
            list of all the sub-account groups

        Examples
        --------
        from brevo import Brevo

        client = Brevo(
            api_key="YOUR_API_KEY",
        )
        client.master_account.get_sub_account_groups()
        """
        _response = self._raw_client.get_sub_account_groups(request_options=request_options)
        return _response.data

    def get_corporate_invited_users_list(
        self,
        *,
        type: typing.Optional[str] = None,
        offset: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetCorporateInvitedUsersListResponse:
        """
        This endpoint allows you to list all Admin users of your Admin account. You
        can filter users by type (active or pending) and paginate results using
        offset and limit.

        Parameters
        ----------
        type : typing.Optional[str]
            User type (active | pending). This is required if offset is provided for
            limited result.

        offset : typing.Optional[int]
            Page number for the result set. This is optional, default value will be
            the 1st page.

        limit : typing.Optional[int]
            Number of users to be displayed on each page. This is optional, the
            default limit is 20, but max allowed limit is 100.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetCorporateInvitedUsersListResponse
            list of all admin users

        Examples
        --------
        from brevo import Brevo

        client = Brevo(
            api_key="YOUR_API_KEY",
        )
        client.master_account.get_corporate_invited_users_list()
        """
        _response = self._raw_client.get_corporate_invited_users_list(
            type=type, offset=offset, limit=limit, request_options=request_options
        )
        return _response.data

    def list_of_all_i_ps(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[GetCorporateIpResponseItem]:
        """
        This endpoint allows you to retrieve the list of active IPs on your Admin
        account

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[GetCorporateIpResponseItem]
            List of all IPs

        Examples
        --------
        from brevo import Brevo

        client = Brevo(
            api_key="YOUR_API_KEY",
        )
        client.master_account.list_of_all_i_ps()
        """
        _response = self._raw_client.list_of_all_i_ps(request_options=request_options)
        return _response.data

    def get_the_details_of_requested_master_account(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetCorporateMasterAccountResponse:
        """
        This endpoint will provide the details of the master account.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetCorporateMasterAccountResponse
            Master account details

        Examples
        --------
        from brevo import Brevo

        client = Brevo(
            api_key="YOUR_API_KEY",
        )
        client.master_account.get_the_details_of_requested_master_account()
        """
        _response = self._raw_client.get_the_details_of_requested_master_account(request_options=request_options)
        return _response.data

    def generate_sso_token_to_access_admin_account(
        self, *, email: str, request_options: typing.Optional[RequestOptions] = None
    ) -> GetSsoToken:
        """
        This endpoint generates an SSO token to authenticate and access the admin
        account using the endpoint
        https://account-app.brevo.com/account/login/corporate/sso/[token], where
        [token] will be replaced by the actual token.

        Parameters
        ----------
        email : str
            User email of admin account

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetSsoToken
            Session token

        Examples
        --------
        from brevo import Brevo

        client = Brevo(
            api_key="YOUR_API_KEY",
        )
        client.master_account.generate_sso_token_to_access_admin_account(
            email="vipin+ent-user@brevo.com",
        )
        """
        _response = self._raw_client.generate_sso_token_to_access_admin_account(
            email=email, request_options=request_options
        )
        return _response.data

    def get_the_list_of_all_the_sub_accounts_of_the_master_account(
        self, *, offset: int, limit: int, request_options: typing.Optional[RequestOptions] = None
    ) -> GetCorporateSubAccountResponse:
        """
        This endpoint will provide the list all the sub-accounts of the master
        account.

        Parameters
        ----------
        offset : int
            Index of the first sub-account in the page

        limit : int
            Number of sub-accounts to be displayed on each page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetCorporateSubAccountResponse
            Sub-accounts list

        Examples
        --------
        from brevo import Brevo

        client = Brevo(
            api_key="YOUR_API_KEY",
        )
        client.master_account.get_the_list_of_all_the_sub_accounts_of_the_master_account(
            offset=1,
            limit=1,
        )
        """
        _response = self._raw_client.get_the_list_of_all_the_sub_accounts_of_the_master_account(
            offset=offset, limit=limit, request_options=request_options
        )
        return _response.data

    def create_a_new_sub_account_under_a_master_account(
        self,
        *,
        company_name: str,
        email: str,
        group_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        language: typing.Optional[PostCorporateSubAccountRequestLanguage] = OMIT,
        timezone: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostCorporateSubAccountResponse:
        """
        This endpoint will create a new sub-account under a master account

        Parameters
        ----------
        company_name : str
            Set the name of the sub-account company

        email : str
            Email address for the organization

        group_ids : typing.Optional[typing.Sequence[str]]
            Set the group(s) for the sub-account

        language : typing.Optional[PostCorporateSubAccountRequestLanguage]
            Set the language of the sub-account

        timezone : typing.Optional[str]
            Set the timezone of the sub-account

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostCorporateSubAccountResponse
            Created sub-account ID

        Examples
        --------
        from brevo import Brevo

        client = Brevo(
            api_key="YOUR_API_KEY",
        )
        client.master_account.create_a_new_sub_account_under_a_master_account(
            company_name="Test Sub-account",
            email="test-sub@example.com",
            group_ids=["5f8f8c3b5f56a02d4433b3a7", "5f8f8c3b5f56a02d4433b3a8"],
            language="fr",
            timezone="Europe/Paris",
        )
        """
        _response = self._raw_client.create_a_new_sub_account_under_a_master_account(
            company_name=company_name,
            email=email,
            group_ids=group_ids,
            language=language,
            timezone=timezone,
            request_options=request_options,
        )
        return _response.data

    def associate_an_ip_to_sub_accounts(
        self, *, ids: typing.Sequence[int], ip: str, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        This endpoint allows to associate an IP to sub-accounts

        Parameters
        ----------
        ids : typing.Sequence[int]
            Pass the list of sub-account Ids to be associated with the IP
            address

        ip : str
            IP address

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            IP has been associated with sub-accounts successfully

        Examples
        --------
        from brevo import Brevo

        client = Brevo(
            api_key="YOUR_API_KEY",
        )
        client.master_account.associate_an_ip_to_sub_accounts(
            ids=[234322, 325553, 893432],
            ip="103.11.32.88",
        )
        """
        _response = self._raw_client.associate_an_ip_to_sub_accounts(ids=ids, ip=ip, request_options=request_options)
        return _response.data

    def dissociate_an_ip_to_sub_accounts(
        self, *, ids: typing.Sequence[int], ip: str, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        This endpoint allows to dissociate an IP from sub-accounts

        Parameters
        ----------
        ids : typing.Sequence[int]
            Pass the list of sub-account Ids to be dissociated from the IP
            address

        ip : str
            IP address

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from brevo import Brevo

        client = Brevo(
            api_key="YOUR_API_KEY",
        )
        client.master_account.dissociate_an_ip_to_sub_accounts(
            ids=[234322, 325553, 893432],
            ip="103.11.32.88",
        )
        """
        _response = self._raw_client.dissociate_an_ip_to_sub_accounts(ids=ids, ip=ip, request_options=request_options)
        return _response.data

    def create_an_api_key_for_a_sub_account(
        self, *, id: int, name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PostCorporateSubAccountKeyResponse:
        """
        This endpoint will generate an API v3 key for a sub-account

        Parameters
        ----------
        id : int
            Id of the sub-account organization

        name : str
            Name of the API key

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostCorporateSubAccountKeyResponse
            API key

        Examples
        --------
        from brevo import Brevo

        client = Brevo(
            api_key="YOUR_API_KEY",
        )
        client.master_account.create_an_api_key_for_a_sub_account(
            id=3232323,
            name="My Api Key",
        )
        """
        _response = self._raw_client.create_an_api_key_for_a_sub_account(
            id=id, name=name, request_options=request_options
        )
        return _response.data

    def generate_sso_token_to_access_sub_account(
        self,
        *,
        id: int,
        email: typing.Optional[str] = OMIT,
        target: typing.Optional[PostCorporateSubAccountSsoTokenRequestTarget] = OMIT,
        url: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetSsoToken:
        """
        This endpoint generates an sso token to authenticate and access a
        sub-account of the master using the account endpoint
        https://account-app.brevo.com/account/login/sub-account/sso/[token], where
        [token] will be replaced by the actual token.

        Parameters
        ----------
        id : int
            Id of the sub-account organization

        email : typing.Optional[str]
            User email of sub-account organization

        target : typing.Optional[PostCorporateSubAccountSsoTokenRequestTarget]
            **Set target after login success** * **automation** - Redirect
            to Automation after login * **email_campaign** - Redirect to
            Email Campaign after login * **contacts** - Redirect to Contacts
            after login * **landing_pages** - Redirect to Landing Pages
            after login * **email_transactional** - Redirect to Email
            Transactional after login * **senders** - Redirect to Senders
            after login * **sms_campaign** - Redirect to Sms Campaign after
            login * **sms_transactional** - Redirect to Sms Transactional
            after login

        url : typing.Optional[str]
            Set the full target URL after login success. The user will land
            directly on this target URL after login

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetSsoToken
            Session token

        Examples
        --------
        from brevo import Brevo

        client = Brevo(
            api_key="YOUR_API_KEY",
        )
        client.master_account.generate_sso_token_to_access_sub_account(
            id=3232323,
        )
        """
        _response = self._raw_client.generate_sso_token_to_access_sub_account(
            id=id, email=email, target=target, url=url, request_options=request_options
        )
        return _response.data

    def get_sub_account_details(
        self, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetCorporateSubAccountIdResponse:
        """
        This endpoint will provide the details for the specified sub-account company

        Parameters
        ----------
        id : int
            Id of the sub-account organization

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetCorporateSubAccountIdResponse
            Sub-account organization details

        Examples
        --------
        from brevo import Brevo

        client = Brevo(
            api_key="YOUR_API_KEY",
        )
        client.master_account.get_sub_account_details(
            id=1000000,
        )
        """
        _response = self._raw_client.get_sub_account_details(id, request_options=request_options)
        return _response.data

    def delete_a_sub_account(self, id: int, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        id : int
            Id of the sub-account organization to be deleted

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from brevo import Brevo

        client = Brevo(
            api_key="YOUR_API_KEY",
        )
        client.master_account.delete_a_sub_account(
            id=1000000,
        )
        """
        _response = self._raw_client.delete_a_sub_account(id, request_options=request_options)
        return _response.data

    def enable_disable_sub_account_application_s(
        self,
        id: int,
        *,
        automation: typing.Optional[bool] = OMIT,
        conversations: typing.Optional[bool] = OMIT,
        crm: typing.Optional[bool] = OMIT,
        email_campaigns: typing.Optional[bool] = OMIT,
        facebook_ads: typing.Optional[bool] = OMIT,
        inbox: typing.Optional[bool] = OMIT,
        landing_pages: typing.Optional[bool] = OMIT,
        meetings: typing.Optional[bool] = OMIT,
        sms_campaigns: typing.Optional[bool] = OMIT,
        transactional_emails: typing.Optional[bool] = OMIT,
        transactional_sms: typing.Optional[bool] = OMIT,
        web_push: typing.Optional[bool] = OMIT,
        whatsapp: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        API endpoint for the Corporate owner to enable/disable applications on the
        sub-account

        Parameters
        ----------
        id : int
            Id of the sub-account organization (mandatory)

        automation : typing.Optional[bool]
            Set this field to enable or disable Automation on the
            sub-account

        conversations : typing.Optional[bool]
            Set this field to enable or disable Conversations on the
            sub-account

        crm : typing.Optional[bool]
            Set this field to enable or disable Sales CRM on the sub-account

        email_campaigns : typing.Optional[bool]
            Set this field to enable or disable Email Campaigns on the
            sub-account

        facebook_ads : typing.Optional[bool]
            Set this field to enable or disable Facebook ads on the
            sub-account

        inbox : typing.Optional[bool]
            Set this field to enable or disable Inbox on the sub-account /
            Not applicable on ENTv2

        landing_pages : typing.Optional[bool]
            Set this field to enable or disable Landing pages on the
            sub-account

        meetings : typing.Optional[bool]
            Set this field to enable or disable Meetings on the sub-account

        sms_campaigns : typing.Optional[bool]
            Set this field to enable or disable SMS Marketing on the
            sub-account

        transactional_emails : typing.Optional[bool]
            Set this field to enable or disable Transactional Email on the
            sub-account

        transactional_sms : typing.Optional[bool]
            Set this field to enable or disable Transactional SMS on the
            sub-account

        web_push : typing.Optional[bool]
            Set this field to enable or disable Web Push on the sub-account

        whatsapp : typing.Optional[bool]
            Set this field to enable or disable Whatsapp campaigns on the
            sub-account

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from brevo import Brevo

        client = Brevo(
            api_key="YOUR_API_KEY",
        )
        client.master_account.enable_disable_sub_account_application_s(
            id=1000000,
            landing_pages=True,
            meetings=True,
            sms_campaigns=False,
            web_push=False,
            whatsapp=True,
        )
        """
        _response = self._raw_client.enable_disable_sub_account_application_s(
            id,
            automation=automation,
            conversations=conversations,
            crm=crm,
            email_campaigns=email_campaigns,
            facebook_ads=facebook_ads,
            inbox=inbox,
            landing_pages=landing_pages,
            meetings=meetings,
            sms_campaigns=sms_campaigns,
            transactional_emails=transactional_emails,
            transactional_sms=transactional_sms,
            web_push=web_push,
            whatsapp=whatsapp,
            request_options=request_options,
        )
        return _response.data

    def update_sub_account_plan(
        self,
        id: int,
        *,
        credits: typing.Optional[PutCorporateSubAccountIdPlanRequestCredits] = OMIT,
        features: typing.Optional[PutCorporateSubAccountIdPlanRequestFeatures] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        This endpoint will update the sub-account plan. On the Corporate solution
        new version v2, you can set an unlimited number of credits in your
        sub-organization. Please pass the value “-1" to set the consumable in
        unlimited mode.

        Parameters
        ----------
        id : int
            Id of the sub-account organization

        credits : typing.Optional[PutCorporateSubAccountIdPlanRequestCredits]
            Credit details to update

        features : typing.Optional[PutCorporateSubAccountIdPlanRequestFeatures]
            Features details to update

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from brevo import Brevo
        from brevo.master_account import (
            PutCorporateSubAccountIdPlanRequestCredits,
            PutCorporateSubAccountIdPlanRequestFeatures,
        )

        client = Brevo(
            api_key="YOUR_API_KEY",
        )
        client.master_account.update_sub_account_plan(
            id=1000000,
            credits=PutCorporateSubAccountIdPlanRequestCredits(
                email=5000,
                external_feeds=1,
                sms=2000.0,
                whatsapp=100.0,
                wp_subscribers=-1,
            ),
            features=PutCorporateSubAccountIdPlanRequestFeatures(
                inbox=10,
                landing_page=20,
                sales_users=6,
                users=15,
            ),
        )
        """
        _response = self._raw_client.update_sub_account_plan(
            id, credits=credits, features=features, request_options=request_options
        )
        return _response.data

    def update_sub_accounts_plan(
        self,
        *,
        credits: typing.Optional[PutCorporateSubAccountsPlanRequestCredits] = OMIT,
        features: typing.Optional[PutCorporateSubAccountsPlanRequestFeatures] = OMIT,
        sub_account_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        This endpoint will update multiple sub-accounts plan. On the Corporate
        solution new version v2, you can set an unlimited number of credits in your
        sub-organization. Please pass the value “-1" to set the consumable in
        unlimited mode.

        Parameters
        ----------
        credits : typing.Optional[PutCorporateSubAccountsPlanRequestCredits]
            Credit details to update

        features : typing.Optional[PutCorporateSubAccountsPlanRequestFeatures]
            Features details to update

        sub_account_ids : typing.Optional[typing.Sequence[int]]
            List of sub-account ids

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from brevo import Brevo
        from brevo.master_account import (
            PutCorporateSubAccountsPlanRequestCredits,
            PutCorporateSubAccountsPlanRequestFeatures,
        )

        client = Brevo(
            api_key="YOUR_API_KEY",
        )
        client.master_account.update_sub_accounts_plan(
            credits=PutCorporateSubAccountsPlanRequestCredits(
                email=5000,
                external_feeds=1,
                sms=2000.0,
                whatsapp=100.0,
                wp_subscribers=-1,
            ),
            features=PutCorporateSubAccountsPlanRequestFeatures(
                landing_page=20,
                sales_users=6,
                users=15,
            ),
            sub_account_ids=[4534345, 987893, 876785],
        )
        """
        _response = self._raw_client.update_sub_accounts_plan(
            credits=credits, features=features, sub_account_ids=sub_account_ids, request_options=request_options
        )
        return _response.data

    def invite_admin_user(
        self,
        *,
        all_features_access: bool,
        email: str,
        privileges: typing.Sequence[InviteAdminUserRequestPrivilegesItem],
        group_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> InviteAdminUserResponse:
        """
        `This endpoint allows you to invite a member to manage the Admin account
        Features and their respective permissions are as below: - `my_plan`:
          - "all"
        - `api`:
          - "none"
        - `user_management`:
          - "all"
        - `app_management` | Not available in ENTv2:
          - "all"
        - `sub_organization_groups`
          - "create"
          - "edit_delete"
        - `create_sub_organizations`
          - "all"
        - `manage_sub_organizations`
          - "all"
        - `analytics`
          - "download_data"
          - "create_alerts"
          - "my_looks"
          - "explore_create"
        - `security`
          - "all"
        **Note**: - If `all_features_access: false` then only privileges are
        required otherwise if `true` then it's assumed that all permissions will be
        there for the invited admin user.

        Parameters
        ----------
        all_features_access : bool
            All access to the features

        email : str
            Email address for the organization

        privileges : typing.Sequence[InviteAdminUserRequestPrivilegesItem]

        group_ids : typing.Optional[typing.Sequence[str]]
            Ids of Group

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InviteAdminUserResponse
            Invitation ID

        Examples
        --------
        from brevo import Brevo
        from brevo.master_account import InviteAdminUserRequestPrivilegesItem

        client = Brevo(
            api_key="YOUR_API_KEY",
        )
        client.master_account.invite_admin_user(
            all_features_access=True,
            email="inviteuser@example.com",
            privileges=[InviteAdminUserRequestPrivilegesItem()],
        )
        """
        _response = self._raw_client.invite_admin_user(
            all_features_access=all_features_access,
            email=email,
            privileges=privileges,
            group_ids=group_ids,
            request_options=request_options,
        )
        return _response.data

    def resend_cancel_admin_user_invitation(
        self,
        action: PutCorporateUserInvitationActionEmailRequestAction,
        email: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PutCorporateUserInvitationActionEmailResponse:
        """
        This endpoint will allow the user to:
        - Resend an admin user invitation
        - Cancel an admin user invitation

        Parameters
        ----------
        action : PutCorporateUserInvitationActionEmailRequestAction
            Action to be performed (cancel / resend)

        email : str
            Email address of the recipient

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PutCorporateUserInvitationActionEmailResponse
            Response of the action performed

        Examples
        --------
        from brevo import Brevo

        client = Brevo(
            api_key="YOUR_API_KEY",
        )
        client.master_account.resend_cancel_admin_user_invitation(
            action="resend",
            email="email",
        )
        """
        _response = self._raw_client.resend_cancel_admin_user_invitation(action, email, request_options=request_options)
        return _response.data

    def revoke_an_admin_user(self, email: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        This endpoint allows to revoke/remove an invited member of your Admin
        account

        Parameters
        ----------
        email : str
            Email of the invited user

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from brevo import Brevo

        client = Brevo(
            api_key="YOUR_API_KEY",
        )
        client.master_account.revoke_an_admin_user(
            email="email",
        )
        """
        _response = self._raw_client.revoke_an_admin_user(email, request_options=request_options)
        return _response.data

    def get_corporate_user_permission(
        self, email: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetCorporateUserPermissionResponse:
        """
        This endpoint will provide the list of admin user permissions

        Parameters
        ----------
        email : str
            Email of the invited user.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetCorporateUserPermissionResponse
            List of user's permissions

        Examples
        --------
        from brevo import Brevo

        client = Brevo(
            api_key="YOUR_API_KEY",
        )
        client.master_account.get_corporate_user_permission(
            email="email",
        )
        """
        _response = self._raw_client.get_corporate_user_permission(email, request_options=request_options)
        return _response.data

    def change_admin_user_permissions(
        self,
        email: str,
        *,
        all_features_access: bool,
        privileges: typing.Sequence[PutCorporateUserEmailPermissionsRequestPrivilegesItem],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        This endpoint will allow you to change the permissions of Admin users of
        your Admin account

        Parameters
        ----------
        email : str
            Email address of Admin user

        all_features_access : bool
            All access to the features

        privileges : typing.Sequence[PutCorporateUserEmailPermissionsRequestPrivilegesItem]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from brevo import Brevo
        from brevo.master_account import (
            PutCorporateUserEmailPermissionsRequestPrivilegesItem,
        )

        client = Brevo(
            api_key="YOUR_API_KEY",
        )
        client.master_account.change_admin_user_permissions(
            email="email",
            all_features_access=False,
            privileges=[
                PutCorporateUserEmailPermissionsRequestPrivilegesItem(
                    feature="user_management",
                    permissions=["all"],
                ),
                PutCorporateUserEmailPermissionsRequestPrivilegesItem(
                    feature="api",
                    permissions=["all"],
                ),
                PutCorporateUserEmailPermissionsRequestPrivilegesItem(
                    feature="my_plan",
                    permissions=["none"],
                ),
                PutCorporateUserEmailPermissionsRequestPrivilegesItem(
                    feature="apps_management",
                    permissions=["all"],
                ),
                PutCorporateUserEmailPermissionsRequestPrivilegesItem(
                    feature="create_sub_organizations",
                    permissions=["all"],
                ),
                PutCorporateUserEmailPermissionsRequestPrivilegesItem(
                    feature="sub_organization_groups",
                    permissions=["create", "edit_delete"],
                ),
                PutCorporateUserEmailPermissionsRequestPrivilegesItem(
                    feature="manage_sub_organizations",
                    permissions=["all"],
                ),
                PutCorporateUserEmailPermissionsRequestPrivilegesItem(
                    feature="security",
                    permissions=["none"],
                ),
                PutCorporateUserEmailPermissionsRequestPrivilegesItem(
                    feature="analytics",
                    permissions=[
                        "create_alerts",
                        "download_data",
                        "my_looks",
                        "explore_create",
                    ],
                ),
            ],
        )
        """
        _response = self._raw_client.change_admin_user_permissions(
            email, all_features_access=all_features_access, privileges=privileges, request_options=request_options
        )
        return _response.data


class AsyncMasterAccountClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMasterAccountClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMasterAccountClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMasterAccountClient
        """
        return self._raw_client

    async def create_a_new_group_of_sub_accounts(
        self,
        *,
        group_name: str,
        sub_account_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostCorporateGroupResponse:
        """
        This endpoint allows to create a group of sub-accounts

        Parameters
        ----------
        group_name : str
            The name of the group of sub-accounts

        sub_account_ids : typing.Optional[typing.Sequence[int]]
            Pass the list of sub-account Ids to be included in the group

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostCorporateGroupResponse
            Group ID

        Examples
        --------
        import asyncio

        from brevo import AsyncBrevo

        client = AsyncBrevo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.master_account.create_a_new_group_of_sub_accounts(
                group_name="My group",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_a_new_group_of_sub_accounts(
            group_name=group_name, sub_account_ids=sub_account_ids, request_options=request_options
        )
        return _response.data

    async def delete_sub_account_from_group(
        self,
        group_id: str,
        *,
        sub_account_ids: typing.Sequence[int],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        This endpoint allows you to remove a sub-organization from a group.

        Parameters
        ----------
        group_id : str
            Group id

        sub_account_ids : typing.Sequence[int]
            List of sub-account ids

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from brevo import AsyncBrevo

        client = AsyncBrevo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.master_account.delete_sub_account_from_group(
                group_id="groupId",
                sub_account_ids=[423432, 234323, 87678],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_sub_account_from_group(
            group_id, sub_account_ids=sub_account_ids, request_options=request_options
        )
        return _response.data

    async def get_a_group_details(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetCorporateGroupIdResponse:
        """
        This endpoint allows you to retrieve a specific group’s information such as
        the list of sub-organizations and the user associated with the group.

        Parameters
        ----------
        id : str
            Id of the group of sub-organization

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetCorporateGroupIdResponse
            Group details

        Examples
        --------
        import asyncio

        from brevo import AsyncBrevo

        client = AsyncBrevo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.master_account.get_a_group_details(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_a_group_details(id, request_options=request_options)
        return _response.data

    async def update_a_group_of_sub_accounts(
        self,
        id: str,
        *,
        group_name: typing.Optional[str] = OMIT,
        sub_account_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        This endpoint allows to update a group of sub-accounts

        Parameters
        ----------
        id : str
            Id of the group

        group_name : typing.Optional[str]
            The name of the group of sub-accounts

        sub_account_ids : typing.Optional[typing.Sequence[int]]
            Pass the list of sub-account Ids to be included in the group

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from brevo import AsyncBrevo

        client = AsyncBrevo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.master_account.update_a_group_of_sub_accounts(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_a_group_of_sub_accounts(
            id, group_name=group_name, sub_account_ids=sub_account_ids, request_options=request_options
        )
        return _response.data

    async def delete_a_group(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        This endpoint allows you to delete a group of sub-organizations. When a
        group is deleted, the sub-organizations are no longer part of this group.
        The users associated with the group are no longer associated with the group
        once deleted.

        Parameters
        ----------
        id : str
            Id of the group

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from brevo import AsyncBrevo

        client = AsyncBrevo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.master_account.delete_a_group(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_a_group(id, request_options=request_options)
        return _response.data

    async def get_sub_account_groups(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[GetSubAccountGroupsResponseItem]:
        """
        This endpoint allows you to list all groups created on your Admin account.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[GetSubAccountGroupsResponseItem]
            list of all the sub-account groups

        Examples
        --------
        import asyncio

        from brevo import AsyncBrevo

        client = AsyncBrevo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.master_account.get_sub_account_groups()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_sub_account_groups(request_options=request_options)
        return _response.data

    async def get_corporate_invited_users_list(
        self,
        *,
        type: typing.Optional[str] = None,
        offset: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetCorporateInvitedUsersListResponse:
        """
        This endpoint allows you to list all Admin users of your Admin account. You
        can filter users by type (active or pending) and paginate results using
        offset and limit.

        Parameters
        ----------
        type : typing.Optional[str]
            User type (active | pending). This is required if offset is provided for
            limited result.

        offset : typing.Optional[int]
            Page number for the result set. This is optional, default value will be
            the 1st page.

        limit : typing.Optional[int]
            Number of users to be displayed on each page. This is optional, the
            default limit is 20, but max allowed limit is 100.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetCorporateInvitedUsersListResponse
            list of all admin users

        Examples
        --------
        import asyncio

        from brevo import AsyncBrevo

        client = AsyncBrevo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.master_account.get_corporate_invited_users_list()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_corporate_invited_users_list(
            type=type, offset=offset, limit=limit, request_options=request_options
        )
        return _response.data

    async def list_of_all_i_ps(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[GetCorporateIpResponseItem]:
        """
        This endpoint allows you to retrieve the list of active IPs on your Admin
        account

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[GetCorporateIpResponseItem]
            List of all IPs

        Examples
        --------
        import asyncio

        from brevo import AsyncBrevo

        client = AsyncBrevo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.master_account.list_of_all_i_ps()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_of_all_i_ps(request_options=request_options)
        return _response.data

    async def get_the_details_of_requested_master_account(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetCorporateMasterAccountResponse:
        """
        This endpoint will provide the details of the master account.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetCorporateMasterAccountResponse
            Master account details

        Examples
        --------
        import asyncio

        from brevo import AsyncBrevo

        client = AsyncBrevo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.master_account.get_the_details_of_requested_master_account()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_the_details_of_requested_master_account(request_options=request_options)
        return _response.data

    async def generate_sso_token_to_access_admin_account(
        self, *, email: str, request_options: typing.Optional[RequestOptions] = None
    ) -> GetSsoToken:
        """
        This endpoint generates an SSO token to authenticate and access the admin
        account using the endpoint
        https://account-app.brevo.com/account/login/corporate/sso/[token], where
        [token] will be replaced by the actual token.

        Parameters
        ----------
        email : str
            User email of admin account

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetSsoToken
            Session token

        Examples
        --------
        import asyncio

        from brevo import AsyncBrevo

        client = AsyncBrevo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.master_account.generate_sso_token_to_access_admin_account(
                email="vipin+ent-user@brevo.com",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.generate_sso_token_to_access_admin_account(
            email=email, request_options=request_options
        )
        return _response.data

    async def get_the_list_of_all_the_sub_accounts_of_the_master_account(
        self, *, offset: int, limit: int, request_options: typing.Optional[RequestOptions] = None
    ) -> GetCorporateSubAccountResponse:
        """
        This endpoint will provide the list all the sub-accounts of the master
        account.

        Parameters
        ----------
        offset : int
            Index of the first sub-account in the page

        limit : int
            Number of sub-accounts to be displayed on each page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetCorporateSubAccountResponse
            Sub-accounts list

        Examples
        --------
        import asyncio

        from brevo import AsyncBrevo

        client = AsyncBrevo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.master_account.get_the_list_of_all_the_sub_accounts_of_the_master_account(
                offset=1,
                limit=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_the_list_of_all_the_sub_accounts_of_the_master_account(
            offset=offset, limit=limit, request_options=request_options
        )
        return _response.data

    async def create_a_new_sub_account_under_a_master_account(
        self,
        *,
        company_name: str,
        email: str,
        group_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        language: typing.Optional[PostCorporateSubAccountRequestLanguage] = OMIT,
        timezone: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostCorporateSubAccountResponse:
        """
        This endpoint will create a new sub-account under a master account

        Parameters
        ----------
        company_name : str
            Set the name of the sub-account company

        email : str
            Email address for the organization

        group_ids : typing.Optional[typing.Sequence[str]]
            Set the group(s) for the sub-account

        language : typing.Optional[PostCorporateSubAccountRequestLanguage]
            Set the language of the sub-account

        timezone : typing.Optional[str]
            Set the timezone of the sub-account

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostCorporateSubAccountResponse
            Created sub-account ID

        Examples
        --------
        import asyncio

        from brevo import AsyncBrevo

        client = AsyncBrevo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.master_account.create_a_new_sub_account_under_a_master_account(
                company_name="Test Sub-account",
                email="test-sub@example.com",
                group_ids=["5f8f8c3b5f56a02d4433b3a7", "5f8f8c3b5f56a02d4433b3a8"],
                language="fr",
                timezone="Europe/Paris",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_a_new_sub_account_under_a_master_account(
            company_name=company_name,
            email=email,
            group_ids=group_ids,
            language=language,
            timezone=timezone,
            request_options=request_options,
        )
        return _response.data

    async def associate_an_ip_to_sub_accounts(
        self, *, ids: typing.Sequence[int], ip: str, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        This endpoint allows to associate an IP to sub-accounts

        Parameters
        ----------
        ids : typing.Sequence[int]
            Pass the list of sub-account Ids to be associated with the IP
            address

        ip : str
            IP address

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            IP has been associated with sub-accounts successfully

        Examples
        --------
        import asyncio

        from brevo import AsyncBrevo

        client = AsyncBrevo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.master_account.associate_an_ip_to_sub_accounts(
                ids=[234322, 325553, 893432],
                ip="103.11.32.88",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.associate_an_ip_to_sub_accounts(
            ids=ids, ip=ip, request_options=request_options
        )
        return _response.data

    async def dissociate_an_ip_to_sub_accounts(
        self, *, ids: typing.Sequence[int], ip: str, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        This endpoint allows to dissociate an IP from sub-accounts

        Parameters
        ----------
        ids : typing.Sequence[int]
            Pass the list of sub-account Ids to be dissociated from the IP
            address

        ip : str
            IP address

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from brevo import AsyncBrevo

        client = AsyncBrevo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.master_account.dissociate_an_ip_to_sub_accounts(
                ids=[234322, 325553, 893432],
                ip="103.11.32.88",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.dissociate_an_ip_to_sub_accounts(
            ids=ids, ip=ip, request_options=request_options
        )
        return _response.data

    async def create_an_api_key_for_a_sub_account(
        self, *, id: int, name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PostCorporateSubAccountKeyResponse:
        """
        This endpoint will generate an API v3 key for a sub-account

        Parameters
        ----------
        id : int
            Id of the sub-account organization

        name : str
            Name of the API key

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostCorporateSubAccountKeyResponse
            API key

        Examples
        --------
        import asyncio

        from brevo import AsyncBrevo

        client = AsyncBrevo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.master_account.create_an_api_key_for_a_sub_account(
                id=3232323,
                name="My Api Key",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_an_api_key_for_a_sub_account(
            id=id, name=name, request_options=request_options
        )
        return _response.data

    async def generate_sso_token_to_access_sub_account(
        self,
        *,
        id: int,
        email: typing.Optional[str] = OMIT,
        target: typing.Optional[PostCorporateSubAccountSsoTokenRequestTarget] = OMIT,
        url: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetSsoToken:
        """
        This endpoint generates an sso token to authenticate and access a
        sub-account of the master using the account endpoint
        https://account-app.brevo.com/account/login/sub-account/sso/[token], where
        [token] will be replaced by the actual token.

        Parameters
        ----------
        id : int
            Id of the sub-account organization

        email : typing.Optional[str]
            User email of sub-account organization

        target : typing.Optional[PostCorporateSubAccountSsoTokenRequestTarget]
            **Set target after login success** * **automation** - Redirect
            to Automation after login * **email_campaign** - Redirect to
            Email Campaign after login * **contacts** - Redirect to Contacts
            after login * **landing_pages** - Redirect to Landing Pages
            after login * **email_transactional** - Redirect to Email
            Transactional after login * **senders** - Redirect to Senders
            after login * **sms_campaign** - Redirect to Sms Campaign after
            login * **sms_transactional** - Redirect to Sms Transactional
            after login

        url : typing.Optional[str]
            Set the full target URL after login success. The user will land
            directly on this target URL after login

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetSsoToken
            Session token

        Examples
        --------
        import asyncio

        from brevo import AsyncBrevo

        client = AsyncBrevo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.master_account.generate_sso_token_to_access_sub_account(
                id=3232323,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.generate_sso_token_to_access_sub_account(
            id=id, email=email, target=target, url=url, request_options=request_options
        )
        return _response.data

    async def get_sub_account_details(
        self, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetCorporateSubAccountIdResponse:
        """
        This endpoint will provide the details for the specified sub-account company

        Parameters
        ----------
        id : int
            Id of the sub-account organization

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetCorporateSubAccountIdResponse
            Sub-account organization details

        Examples
        --------
        import asyncio

        from brevo import AsyncBrevo

        client = AsyncBrevo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.master_account.get_sub_account_details(
                id=1000000,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_sub_account_details(id, request_options=request_options)
        return _response.data

    async def delete_a_sub_account(self, id: int, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        id : int
            Id of the sub-account organization to be deleted

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from brevo import AsyncBrevo

        client = AsyncBrevo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.master_account.delete_a_sub_account(
                id=1000000,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_a_sub_account(id, request_options=request_options)
        return _response.data

    async def enable_disable_sub_account_application_s(
        self,
        id: int,
        *,
        automation: typing.Optional[bool] = OMIT,
        conversations: typing.Optional[bool] = OMIT,
        crm: typing.Optional[bool] = OMIT,
        email_campaigns: typing.Optional[bool] = OMIT,
        facebook_ads: typing.Optional[bool] = OMIT,
        inbox: typing.Optional[bool] = OMIT,
        landing_pages: typing.Optional[bool] = OMIT,
        meetings: typing.Optional[bool] = OMIT,
        sms_campaigns: typing.Optional[bool] = OMIT,
        transactional_emails: typing.Optional[bool] = OMIT,
        transactional_sms: typing.Optional[bool] = OMIT,
        web_push: typing.Optional[bool] = OMIT,
        whatsapp: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        API endpoint for the Corporate owner to enable/disable applications on the
        sub-account

        Parameters
        ----------
        id : int
            Id of the sub-account organization (mandatory)

        automation : typing.Optional[bool]
            Set this field to enable or disable Automation on the
            sub-account

        conversations : typing.Optional[bool]
            Set this field to enable or disable Conversations on the
            sub-account

        crm : typing.Optional[bool]
            Set this field to enable or disable Sales CRM on the sub-account

        email_campaigns : typing.Optional[bool]
            Set this field to enable or disable Email Campaigns on the
            sub-account

        facebook_ads : typing.Optional[bool]
            Set this field to enable or disable Facebook ads on the
            sub-account

        inbox : typing.Optional[bool]
            Set this field to enable or disable Inbox on the sub-account /
            Not applicable on ENTv2

        landing_pages : typing.Optional[bool]
            Set this field to enable or disable Landing pages on the
            sub-account

        meetings : typing.Optional[bool]
            Set this field to enable or disable Meetings on the sub-account

        sms_campaigns : typing.Optional[bool]
            Set this field to enable or disable SMS Marketing on the
            sub-account

        transactional_emails : typing.Optional[bool]
            Set this field to enable or disable Transactional Email on the
            sub-account

        transactional_sms : typing.Optional[bool]
            Set this field to enable or disable Transactional SMS on the
            sub-account

        web_push : typing.Optional[bool]
            Set this field to enable or disable Web Push on the sub-account

        whatsapp : typing.Optional[bool]
            Set this field to enable or disable Whatsapp campaigns on the
            sub-account

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from brevo import AsyncBrevo

        client = AsyncBrevo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.master_account.enable_disable_sub_account_application_s(
                id=1000000,
                landing_pages=True,
                meetings=True,
                sms_campaigns=False,
                web_push=False,
                whatsapp=True,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.enable_disable_sub_account_application_s(
            id,
            automation=automation,
            conversations=conversations,
            crm=crm,
            email_campaigns=email_campaigns,
            facebook_ads=facebook_ads,
            inbox=inbox,
            landing_pages=landing_pages,
            meetings=meetings,
            sms_campaigns=sms_campaigns,
            transactional_emails=transactional_emails,
            transactional_sms=transactional_sms,
            web_push=web_push,
            whatsapp=whatsapp,
            request_options=request_options,
        )
        return _response.data

    async def update_sub_account_plan(
        self,
        id: int,
        *,
        credits: typing.Optional[PutCorporateSubAccountIdPlanRequestCredits] = OMIT,
        features: typing.Optional[PutCorporateSubAccountIdPlanRequestFeatures] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        This endpoint will update the sub-account plan. On the Corporate solution
        new version v2, you can set an unlimited number of credits in your
        sub-organization. Please pass the value “-1" to set the consumable in
        unlimited mode.

        Parameters
        ----------
        id : int
            Id of the sub-account organization

        credits : typing.Optional[PutCorporateSubAccountIdPlanRequestCredits]
            Credit details to update

        features : typing.Optional[PutCorporateSubAccountIdPlanRequestFeatures]
            Features details to update

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from brevo import AsyncBrevo
        from brevo.master_account import (
            PutCorporateSubAccountIdPlanRequestCredits,
            PutCorporateSubAccountIdPlanRequestFeatures,
        )

        client = AsyncBrevo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.master_account.update_sub_account_plan(
                id=1000000,
                credits=PutCorporateSubAccountIdPlanRequestCredits(
                    email=5000,
                    external_feeds=1,
                    sms=2000.0,
                    whatsapp=100.0,
                    wp_subscribers=-1,
                ),
                features=PutCorporateSubAccountIdPlanRequestFeatures(
                    inbox=10,
                    landing_page=20,
                    sales_users=6,
                    users=15,
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_sub_account_plan(
            id, credits=credits, features=features, request_options=request_options
        )
        return _response.data

    async def update_sub_accounts_plan(
        self,
        *,
        credits: typing.Optional[PutCorporateSubAccountsPlanRequestCredits] = OMIT,
        features: typing.Optional[PutCorporateSubAccountsPlanRequestFeatures] = OMIT,
        sub_account_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        This endpoint will update multiple sub-accounts plan. On the Corporate
        solution new version v2, you can set an unlimited number of credits in your
        sub-organization. Please pass the value “-1" to set the consumable in
        unlimited mode.

        Parameters
        ----------
        credits : typing.Optional[PutCorporateSubAccountsPlanRequestCredits]
            Credit details to update

        features : typing.Optional[PutCorporateSubAccountsPlanRequestFeatures]
            Features details to update

        sub_account_ids : typing.Optional[typing.Sequence[int]]
            List of sub-account ids

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from brevo import AsyncBrevo
        from brevo.master_account import (
            PutCorporateSubAccountsPlanRequestCredits,
            PutCorporateSubAccountsPlanRequestFeatures,
        )

        client = AsyncBrevo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.master_account.update_sub_accounts_plan(
                credits=PutCorporateSubAccountsPlanRequestCredits(
                    email=5000,
                    external_feeds=1,
                    sms=2000.0,
                    whatsapp=100.0,
                    wp_subscribers=-1,
                ),
                features=PutCorporateSubAccountsPlanRequestFeatures(
                    landing_page=20,
                    sales_users=6,
                    users=15,
                ),
                sub_account_ids=[4534345, 987893, 876785],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_sub_accounts_plan(
            credits=credits, features=features, sub_account_ids=sub_account_ids, request_options=request_options
        )
        return _response.data

    async def invite_admin_user(
        self,
        *,
        all_features_access: bool,
        email: str,
        privileges: typing.Sequence[InviteAdminUserRequestPrivilegesItem],
        group_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> InviteAdminUserResponse:
        """
        `This endpoint allows you to invite a member to manage the Admin account
        Features and their respective permissions are as below: - `my_plan`:
          - "all"
        - `api`:
          - "none"
        - `user_management`:
          - "all"
        - `app_management` | Not available in ENTv2:
          - "all"
        - `sub_organization_groups`
          - "create"
          - "edit_delete"
        - `create_sub_organizations`
          - "all"
        - `manage_sub_organizations`
          - "all"
        - `analytics`
          - "download_data"
          - "create_alerts"
          - "my_looks"
          - "explore_create"
        - `security`
          - "all"
        **Note**: - If `all_features_access: false` then only privileges are
        required otherwise if `true` then it's assumed that all permissions will be
        there for the invited admin user.

        Parameters
        ----------
        all_features_access : bool
            All access to the features

        email : str
            Email address for the organization

        privileges : typing.Sequence[InviteAdminUserRequestPrivilegesItem]

        group_ids : typing.Optional[typing.Sequence[str]]
            Ids of Group

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InviteAdminUserResponse
            Invitation ID

        Examples
        --------
        import asyncio

        from brevo import AsyncBrevo
        from brevo.master_account import InviteAdminUserRequestPrivilegesItem

        client = AsyncBrevo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.master_account.invite_admin_user(
                all_features_access=True,
                email="inviteuser@example.com",
                privileges=[InviteAdminUserRequestPrivilegesItem()],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.invite_admin_user(
            all_features_access=all_features_access,
            email=email,
            privileges=privileges,
            group_ids=group_ids,
            request_options=request_options,
        )
        return _response.data

    async def resend_cancel_admin_user_invitation(
        self,
        action: PutCorporateUserInvitationActionEmailRequestAction,
        email: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PutCorporateUserInvitationActionEmailResponse:
        """
        This endpoint will allow the user to:
        - Resend an admin user invitation
        - Cancel an admin user invitation

        Parameters
        ----------
        action : PutCorporateUserInvitationActionEmailRequestAction
            Action to be performed (cancel / resend)

        email : str
            Email address of the recipient

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PutCorporateUserInvitationActionEmailResponse
            Response of the action performed

        Examples
        --------
        import asyncio

        from brevo import AsyncBrevo

        client = AsyncBrevo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.master_account.resend_cancel_admin_user_invitation(
                action="resend",
                email="email",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.resend_cancel_admin_user_invitation(
            action, email, request_options=request_options
        )
        return _response.data

    async def revoke_an_admin_user(
        self, email: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        This endpoint allows to revoke/remove an invited member of your Admin
        account

        Parameters
        ----------
        email : str
            Email of the invited user

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from brevo import AsyncBrevo

        client = AsyncBrevo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.master_account.revoke_an_admin_user(
                email="email",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.revoke_an_admin_user(email, request_options=request_options)
        return _response.data

    async def get_corporate_user_permission(
        self, email: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetCorporateUserPermissionResponse:
        """
        This endpoint will provide the list of admin user permissions

        Parameters
        ----------
        email : str
            Email of the invited user.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetCorporateUserPermissionResponse
            List of user's permissions

        Examples
        --------
        import asyncio

        from brevo import AsyncBrevo

        client = AsyncBrevo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.master_account.get_corporate_user_permission(
                email="email",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_corporate_user_permission(email, request_options=request_options)
        return _response.data

    async def change_admin_user_permissions(
        self,
        email: str,
        *,
        all_features_access: bool,
        privileges: typing.Sequence[PutCorporateUserEmailPermissionsRequestPrivilegesItem],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        This endpoint will allow you to change the permissions of Admin users of
        your Admin account

        Parameters
        ----------
        email : str
            Email address of Admin user

        all_features_access : bool
            All access to the features

        privileges : typing.Sequence[PutCorporateUserEmailPermissionsRequestPrivilegesItem]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from brevo import AsyncBrevo
        from brevo.master_account import (
            PutCorporateUserEmailPermissionsRequestPrivilegesItem,
        )

        client = AsyncBrevo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.master_account.change_admin_user_permissions(
                email="email",
                all_features_access=False,
                privileges=[
                    PutCorporateUserEmailPermissionsRequestPrivilegesItem(
                        feature="user_management",
                        permissions=["all"],
                    ),
                    PutCorporateUserEmailPermissionsRequestPrivilegesItem(
                        feature="api",
                        permissions=["all"],
                    ),
                    PutCorporateUserEmailPermissionsRequestPrivilegesItem(
                        feature="my_plan",
                        permissions=["none"],
                    ),
                    PutCorporateUserEmailPermissionsRequestPrivilegesItem(
                        feature="apps_management",
                        permissions=["all"],
                    ),
                    PutCorporateUserEmailPermissionsRequestPrivilegesItem(
                        feature="create_sub_organizations",
                        permissions=["all"],
                    ),
                    PutCorporateUserEmailPermissionsRequestPrivilegesItem(
                        feature="sub_organization_groups",
                        permissions=["create", "edit_delete"],
                    ),
                    PutCorporateUserEmailPermissionsRequestPrivilegesItem(
                        feature="manage_sub_organizations",
                        permissions=["all"],
                    ),
                    PutCorporateUserEmailPermissionsRequestPrivilegesItem(
                        feature="security",
                        permissions=["none"],
                    ),
                    PutCorporateUserEmailPermissionsRequestPrivilegesItem(
                        feature="analytics",
                        permissions=[
                            "create_alerts",
                            "download_data",
                            "my_looks",
                            "explore_create",
                        ],
                    ),
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.change_admin_user_permissions(
            email, all_features_access=all_features_access, privileges=privileges, request_options=request_options
        )
        return _response.data
